### ISSUE TITLE
Sidemenus on both sides?

### ISSUE THREAD

**Issue by andrerfneves** [meteoric/meteor-ionic#102]
For some reason, my sidemenus are loading both sides. If I swipe on the navbar from left to right, the left menu appears (correct), and if i do the same from right to left, the right menu appears (white blank section)

Here's my layout code for the sidemenus

<template name="layout">

  {{#ionSideMenuContainer}}
      {{#ionSideMenus}}
        {{#ionSideMenu}}
        
         <div class="content sideMenu" >
            {{#if currentUser}}
            <div class="list listSideMenu">
              <div class="item itemTop">
                <h3>Menu</h3>
              </div>
              <div class="item" data-ion-menu-close>
                Courses
              </div>
              <div class="item" data-ion-menu-close>
                Professors
              </div>
              <div class="item" data-ion-menu-close>
                Subscriptions
              </div>
              <div class="item itemTop">
                <h3>User</h3>
              </div>
              <div class="item" data-ion-menu-close>
                Profile
              </div>
              <div class="item" data-ion-menu-close>
                Notifications
              </div>
              <div class="item" data-ion-menu-close>
                Log Out
              </div>
            </div>
            {{else}}
            <div class="list listSideMenu">
              <div class="item itemTop">
                <h3>Welcome</h3>
              </div>
              <div class="item" data-ion-menu-close>
                Log In
              </div>
              <div class="item" data-ion-menu-close>
                Register
              </div>
            </div>
            {{/if}}
          </div>
        {{/ionSideMenu}}
      {{/ionSideMenus}}

      {{#ionSideMenuContent}}
        {{#ionBody}}
          {{> ionNavBar }}
          {{#ionNavView}}
            {{> yield}}
          {{/ionNavView}}

          {{#if isAndroid}}
            {{#ionTabs style="android"}}
              {{> ionTab title="Courses" path="coursesList" icon="android-star"}}
              {{> ionTab title="Professors" path="professors" icon="android-time"}}
              {{> ionTab title="Notifications" path="notifications" icon="android-notifications"}}
              {{> ionTab title="Profile" path="profile" icon="android-happy"}}
            {{/ionTabs}}
          {{else}}
            {{#ionTabs style="ios"}}
              {{> ionTab title="Courses" path="coursesList" iconOff="ios-albums-outline" iconOn="ios-albums" class="tab-item-positive"}}
              {{> ionTab title="Professors" path="professors" iconOff="ios-people-outline" iconOn="ios-people" class="tab-item-positive"}}
              {{> ionTab title="Notifications" path="notifications" iconOff="ios-bell-outline" iconOn="ios-bell" class="tab-item-positive"}}
              {{> ionTab title="Profile" path="profile" iconOff="ios-gear-outline" iconOn="ios-gear" class="tab-item-positive"}}
            {{/ionTabs}}
          {{/if}}
        {{/ionBody}}
      {{/ionSideMenuContent}}
    {{/ionSideMenuContainer}}
</template>

Any ideas?

**Comment by connor-baer** [comment]
Have a look at #74.

**Comment by andrerfneves** [comment]
Yup that works. Cheers @connor-baer
