### ISSUE TITLE
Route direction on routes called by javascript

### ISSUE THREAD

**Issue by geritol** [meteoric/meteor-ionic#103]
Hi! can i specify somehow something equvalent to data-nav-direction to a route called by javascript (eg. Router.go())?
Thanks a lot!

**Comment by nickw** [comment]
Good question. I _think_ you can call `Session.set('ionNavDirection', 'back');` before calling `Router.go()` and that should work. Let me know if not.

**Comment by geritol** [comment]
Not working. What i do for know is that I call .click() on a button with the proper attribute.

**Comment by PolGuixe** [comment]
Same problem here but the button is the one generated by {{> quicForm...}}

**Comment by nickw** [comment]
I realize this is ugly, but did you try:
```
Session.set('ionNavDirection', 'back');
Meteor.setTimeout(function() {
  Router.go('wherever');
}, 100);
```

**Comment by PolGuixe** [comment]
In my case I want to trigger it from one of the `AutorForm.hooks`

Here is the code: 

```
AutoForm.hooks({
  'user-categories-form': {
    onSuccess: function (operation, result, template) {
      Session.set('ionNavDirection', 'back');
      Meteor.setTimeout(function () {
        Router.go('wherever');
      }, 100);
    },

    onError: function (operation, error, template) {
      alert(error);
    }
  }
});
```

**Comment by nickw** [comment]
@PolGuixe so does that work?

**Comment by PolGuixe** [comment]
It doesn't :(

**Comment by nickw** [comment]
Obviously we need a real solution here, but in the meantime can't you just manually do what's being done in the event handler?

https://github.com/meteoric/meteor-ionic/blob/c190e8cd67d6180a44357eed871bd115ea008a85/components/ionBody/ionBody.js#L61

```
$('[data-nav-container]').addClass('nav-view-direction-back');
$('[data-navbar-container]').addClass('nav-bar-direction-back');
```

**Comment by PolGuixe** [comment]
Ok, that works!  Many thanks!

Let us know when there will be a more "elegant" solution. 

I´ll paste the working code as a reference: 
```
AutoForm.hooks({
  'user-categories-form': {
    onSuccess: function (operation, result, template) {
      $('[data-nav-container]').addClass('nav-view-direction-back');
      $('[data-navbar-container]').addClass('nav-bar-direction-back');
      Router.go('/settings');
    },

    onError: function (operation, error, template) {
      alert(error);
    }
  }
});
```

**Comment by geritol** [comment]
Not saying this is the best option but here is what I used:
Your nav button (you can hide it optionally)
<a href="/" id="backToMain" class="button button-clear" data-nav-direction="back">{{> ionIcon icon="ios-arrow-back"}}</a>

And then do this when you whant to go back:
    $('#backToMain').click()
