### ISSUE TITLE
ionic cli

### ISSUE THREAD

**Issue by richpowell** [meteoric/meteor-ionic#104]
Ionic has a cli tool that lets you use one png or psd file to generate all the splash / icon sizes.  any one know of a hack to get this to work? or thoughts on integrating the function on this project?

http://ionicframework.com/blog/automating-icons-and-splash-screens/

there is also a meteor thread that aldeed started on this, but no comments after his.. https://github.com/meteor/meteor/issues/3767

**Comment by nickw** [comment]
Yeah, creating a meteor-specific version of this is definitely on my TODO list. In the meantime you might want to check out: https://github.com/ccorcos/meteor-icon-splash-maker

**Comment by aldeed** [comment]
See also http://crater.io/posts/QHNZzJNKzuxhK2mxE

Might be able to get a group to work on this, @nickw

**Comment by aldeed** [comment]
Closed because it's done? Or not doing?

**Comment by nickw** [comment]
I'm not going to try to tackle it right now, and it's probably out of the scope of this specific repo.

**Comment by aldeed** [comment]
OK, I agree. Just curious.
