### ISSUE TITLE
popover doesn't close?

### ISSUE THREAD

**Issue by richpowell** [meteoric/meteor-ionic#111]
I think Im missing something with the popover. 
I have a list of links, they open in the app fine, however the popover doesnt close when i click a link. 
do i need to put some sort of destroy window as a javascript helper? from the code it looks like there is supposed to be a hide / destroyed on a key up.. is key up the same as a click event? 

if i click the background, the popover goes away... but i want it to go away after i make the link click

**Comment by nickw** [comment]
Yeah I guess I didn't consider that when porting it over. I _think_ we can just remove this conditional: https://github.com/meteoric/meteor-ionic/blob/master/components/ionPopover/ionPopover.js#L74.

**Comment by richpowell** [comment]
I should have read the code fully.. of course it was at the bottom :)

now that i include that "popover-backdrop" into the href element class on the template, the thing disappears on the click.. no need to change the code i dont think.. 

thanks for the info.

**Comment by cyprien-pixngraph** [comment]
Thanks for this question, help me too !
