### ISSUE TITLE
How to create only left side menu ?

### ISSUE THREAD

**Issue by MFQ** [meteoric/meteor-ionic#112]
I am developing a mobile app with meteoric, which have left hand side menu only but meteor-ionic is adding menu on both sides. Although I haven't added any right hand side menu but it is show some blank space on right hand side and its drag able event is also active on right hand side, here is a sample video
http://screencast.com/t/b9EeNizro

**Comment by connor-baer** [comment]
Have a look at #74.

**Comment by MFQ** [comment]
its has done something different now my left hand side menu is shown on full screen

**Comment by MFQ** [comment]
How you are creating side menu ? 
this how I am doing going it
https://gist.github.com/MFQ/dadc8f2baf744dc62de0

**Comment by nickw** [comment]
@MFQ that looks correct. Have you tried running `meteor update` to make sure you have the latest versions of all the meteoric packages?

**Comment by wal-nadeem** [comment]
@MFQ any update. are you able to get it fix?

**Comment by MFQ** [comment]
@nickw I have tired "meteor update" and I have removed "meteoric:ionic-sass" and then added it again but still no success.

**Comment by dancering** [comment]
Try this code on your rendered function:

IonSideMenu.snapper.settings({disable: 'right'});

**Comment by MFQ** [comment]
@dancering I have tried your approach but I am getting this error
Exception from Tracker afterFlush function: Can't find variable: IonSideMenu

I guess IonSideMenu is not access in my rendered function, this how I am implementing my rendered function. 


Template.mobileLayout.rendered = function () {
   IonSideMenu.snapper.settings({disable: 'right'});
};

**Comment by dancering** [comment]
I have attached screen to show you how it works. IonSideMenu has to be available on the console. Can you list the packages that are you using?

![captura de pantalla 2015-03-16 a las 11 53 35](https://cloud.githubusercontent.com/assets/583329/6664830/60546308-cbd3-11e4-8e70-14bbfe3d55b3.png)

**Comment by RobGordon406** [comment]
Thanks dancering

Template.layout.rendered = function () {
     IonSideMenu.snapper.settings({disable: 'right'});
};

Solved the issue with a blank menu on the RHS

Cheers

**Comment by dancering** [comment]
Good to know it's working.

@MFQ Please close the issue. Thx.

**Comment by MFQ** [comment]
@dancering i can't access IonSideMenu at my browser console
