### ISSUE TITLE
admob

### ISSUE THREAD

**Issue by richpowell** [meteoric/meteor-ionic#116]
has anyone successfully integrated admob with meteor-ionic? 
im trying to use the cordova plugin : http://plugins.cordova.io/#/package/com.google.cordova.admob
with the notes from a developer who did it with ionic https://blog.nraboy.com/2014/06/using-admob-ionicframework/

but I cant seem to get this to work with meteoric.. 
any suggestions on how to pull this off?
Thanks guys

**Comment by nickw** [comment]
Are you experiencing any specific issues?

**Comment by richpowell** [comment]
My footer is getting overlayed by the served ad.  Is there a way to reposition the footer or view so footer is moved up since ads are shown in the bottom.  
Maybe this can me easily done in with css?

**Comment by nickw** [comment]
Yeah CSS seems like the way to go. I'm thinking you could override the `bottom` value of this:

https://github.com/meteoric/ionic-sass/blob/master/stylesheets/_scaffolding.scss#L29

to be the height of the ad. That way any footers or tabs you add will be positioned above the ad automatically by Ionic.

**Comment by richpowell** [comment]
I have a app.scss and I've tried overriding with 
.ionic-body {
	bottom:50px;
}
and
body,
.ionic-body {
	bottom:50px;
}

neither of which works for me. am I missing something in the css?
