### ISSUE TITLE
Cannot pass parameter to route

### ISSUE THREAD

**Issue by linhkurt** [meteoric/meteor-ionic#117]
Hi, I have problem with the following code:
I want to create the route: /app/:_appId/module/:_id
<pre><code>
{{#each menus}} 
        {{#ionItem path='module.show' _id:this._id  _appId:this.appId iconRight=true}}
            {{> ionIcon icon="ios-checkmark" class="positive"}}
            {{title}} - {{this._id}} -  {{this.appId}}
            {{> ionIcon icon="ios-arrow-right"}}
          {{/ionItem}}  
           
         {{/each}}
</code></pre>

Error:
<pre><code>
Can't have a non-keyword argument
   after a keyword argument
   ...path='module.show' _id:this._id _appId:thi...
</code></pre>

How can I fix this? Thank you.

**Comment by nickw** [comment]
`_appId:this.appId` should be `_appId=this.appId`

**Comment by linhkurt** [comment]
Sorry for not mentioning that I have tried _appId=this.appId before posting this issue, but it didnot work.
For example I have an object <code>author(_id, name)</code> and a route <code>Router.route('author', {path:'/author/:author_id'})</code>
And I do this:
<pre><code>
{{#each authors}} 
        {{#ionItem path='author' author_id:this._id  iconRight=true}}
            {{> ionIcon icon="ios-checkmark" class="positive"}}
            {{name}}
            {{> ionIcon icon="ios-arrow-right"}}
          {{/ionItem}}  
 {{/each}}
</code></pre>
The problem is it does not work if the parameter name in the route is different from the object attribute name. Why?
If I change the route to <code>Router.route('author', {path:'/author/:_id'})</code> then it works.

**Comment by linhkurt** [comment]
@nickw  i would like to re-open this issue since I cannot get it working when parameter's name in the Route and in the template are different.

Please help!

**Comment by nickw** [comment]
This seems like an iron:router issue, not a meteoric issue. But to confirm, have you tried not using an `ionItem` and instead just doing an `<a class="item" href="{{pathFor 'module.show' _id=this._id  _appId=this.appId}}">{{name}}</a>`.

**Comment by linhkurt** [comment]
Hi nickw,

I have tried using a href and it worked even when parameter names are different.

**Comment by nickw** [comment]
@benstr any thoughts on this?

**Comment by benstr** [comment]
@linhkurt do you have a repo I can look at? From your code above I still see `:` instead of `=` for assigning context.
