### ISSUE TITLE
Closing SideMenu when taping on ionSideMenuContent

### ISSUE THREAD

**Issue by fpoirier1** [meteoric/meteor-ionic#120]
I would to be able to close the SideMenu when user tap on the `SideMenuContent`, I don't think this feature is implemented yet, right ?

This is a workaround I came up with.

```
Template.ionSideMenuContainer.events({
  'click .snapjs-left .snap-content' : function(event){
    event.stopPropagation()
    if(!IonSideMenu.snapper.state().state == "closed")
      IonSideMenu.snapper.close();
  }
})

.snapjs-left .snap-content::after,
.snapjs-right .snap-content::after {
  content: " ";
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: $z-index-click-block;
}
```

I would be glad to contribute to implement a cleaner approch. Let me know what are your thoughts on this.

**Comment by nickw** [comment]
You can also add `data-ion-menu-close` to links: https://github.com/meteoric/meteor-ionic/blob/c190e8cd67d6180a44357eed871bd115ea008a85/components/ionBody/ionBody.js#L87

**Comment by fpoirier1** [comment]
Putting `data-ion-menu-close` on every link of the app wouldn't be an optimal solution for this. I was talking about something similar to this https://github.com/driftyco/ionic/blob/master/js/angular/directive/sideMenuContent.js#L63.

**Comment by nickw** [comment]
Oh, so does Ionic always close the side menu when you click links? If so I think we should definitely mimic that behavior.

**Comment by LaPelle** [comment]
You can open and close the side menu with a JS function easily by using `IonSideMenu.snapper.open('left')` to open the left side menu and `IonSideMenu.snapper.close()` to close the side menus.
