### ISSUE TITLE
form in header displays small offset

### ISSUE THREAD

**Issue by dude-awesome** [meteoric/meteor-ionic#125]
![search](https://cloud.githubusercontent.com/assets/3764301/6767329/3541bd40-d02a-11e4-88d6-1513fe495663.png)

http://ionicframework.com/docs/components/#bar-inputs

    {{#contentFor "headerTitle"}}
        <div class="bar bar-header item-input-inset">
            <label class="item-input-wrapper">
                <i class="icon ion-ios7-search placeholder-icon"></i>

                <form id="search-form" novalidate="novalidate" action="action">
                    <input id="username" type="search" placeholder="Search Username">
                </form>
            </label>
            <button class="button button-clear">
                Cancel
            </button>
        </div>
    {{/contentFor}}

how to avoid this small offset in the header? I just can push content on the left/right or in the title via contentFor right?

    <div class="item-input-inset" style="width: 80%">

fix the Problem but I don't like it.

**Comment by nickw** [comment]
I haven't had that issue, but it seems like it's an issue with Ionic's CSS, not our Meteor implementation. I would probably post this on the Ionic repo.
