### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by vko-online** [meteoric/meteor-ionic#126]
But one thing i don't like in meteor is this

    $('body').addClass('keyboard-open');

Those ugly selectors look bad, and using jQuery not good idea, i more like `angular.element` and link functions of directives, they are more readable and reusable
Hope this will be improved in this project

**Comment by vko-online** [comment]
why this closed without reply

**Comment by nickw** [comment]
This is more of a general Meteor discussion / suggestion, I don't think it's  related to meteor-ionic.

**Comment by vko-online** [comment]
i think _meteor + angular-ionic_ is more comfortable, that _meteor + ionic + jquery_

**Comment by geritol** [comment]
Man... If you think so, then use it so!
Read the readme. -->
"I'm not a fan of trying to force-fit Angular into Meteor, so I wanted to see if I could rewrite Ionic specifically for Meteor."
