### ISSUE TITLE
Create a Getting Started guide

### ISSUE THREAD

**Issue by nickw** [meteoric/meteor-ionic#13]
Create some wiki pages for:
- Getting started / installation
- Creating a navigation UI
- Creating a tab UI (with cross-platform UI)
- Modals
- Autoform
- Accounts templates

**Comment by ccorcos** [comment]
+1

Way to go with this project by the way, this is amazing! I'd love to help, but I'm kind of stuck right now because I'm not sure how you get all that animation!

**Comment by nickw** [comment]
@ccorcos do the example apps help in the meantime? If not, I'll try to write something up tonight or tomorrow:

https://github.com/meteoric/contacts
https://github.com/meteoric/meteorhunt

**Comment by ccorcos** [comment]
They do a little bit, but it would be super helpful just to have some kind of guide that helps me understand the design of this project. I don't know much about block helpers `{{#iconic-something}}` and it seems those are used everywhere.

**Comment by ccorcos** [comment]
To answer your question, a 1-2 page guide would be enormously helpful ;)

**Comment by Evrei** [comment]
+1 to guide

**Comment by nickw** [comment]
Ok guys, here's something quick I whipped up: https://github.com/meteoric/meteor-ionic/blob/master/GUIDE.md

Let me know if it's helpful at all, and what else you'd like to see.

**Comment by niallobrien** [comment]
This is pretty awesome. At first I was thinking that surely the styles would be enough, but you quickly realise that there's a lot more to a native feeling app than just the styles. Your demos are very responsive which is great. Eagerly awaiting more directive conversions & docs.

**Comment by benstr** [comment]
@nickw great start on the guide. I like how you explained Blaze `blocks` really well by contracting them to `inclusions`. 

I just built a similar package to **meteor-ionic** but for Material Design (not a public project yet, it was for client work). Looking forward to contributing. Will be building a meteoric app this weekend and will record my development then circle back and make a step-by-step how-to. Bug me next Tuesday if you do not see anything, haha

**Comment by rjakobsson** [comment]
One thing I just noticed is that the backUrl in a nav view is set only when you specify some kind of data in the "data" parameter in your router setting. If you don't set data, it won't work.

**Comment by nickw** [comment]
@rjakobsson can you add a new issue for this? I'm not sure how it's happening since we're grabbing the `backUrl` directly from the template options, and falling back to `history.back()`. If you can post some code in that issue that would be awesome.

**Comment by rjakobsson** [comment]
@nickw Yes I'll do that.

**Comment by hettema** [comment]
@benstr Bugging you as requested. I need all the step-by-steps I can get my hands on ;)

**Comment by benstr** [comment]
@hettema my optimism always gets the best of me. LOL

I got the bones started, check it out, [meteoric-projects](https://github.com/benstr/meteoric-projects).

**Comment by nickw** [comment]
@benstr wow looks great

**Comment by benstr** [comment]
Thanks @nickw. PRs totally welcome by anyone. I just closed on two large projects. With my new schedule I will probably release one chapter a week.

**Comment by everywhereis** [comment]
@benstr dude, that looks awesome!

**Comment by joshua1** [comment]
@benstr I am interested in your package based on material design. can you please make it available or provide pointers as to how you had it done
