### ISSUE TITLE
Text selection when using meteor-ionic

### ISSUE THREAD

**Issue by AnkitTheCoder** [meteoric/meteor-ionic#131]
Is it possible to make text selectable when using meteor-ionic? 

I have managed to overcome most of the bootstrap-ionic conflicts to enable template re-use on mobile as well as desktop. The only thing that stands out is the inability to select text on desktop webpage. In its current state, the web page shows up nice and correct but I cannot select any text.

I am sure that is a valid scenario for mobile phones as well. 

Any way to overcome this issue?

**Comment by nickw** [comment]
You probably just need to override this line: https://github.com/meteoric/ionic-sass/blob/master/stylesheets/_scaffolding.scss#L25
