### ISSUE TITLE
Ionic Material Theme

### ISSUE THREAD

**Issue by joshua1** [meteoric/meteor-ionic#133]
Hi Guys,
How do i use this ionic CSS extension https://github.com/zachsoft/Ionic-Material with meteoric to get the material design look and feel

**Comment by enrq** [comment]
I am also interested on this...

**Comment by nickw** [comment]
If it's just CSS then you'd just need to add their CSS to your project. Did you try it and run into issues?

**Comment by dude-awesome** [comment]
this looks interesting. please give us an information if this works with meteoric.

**Comment by sferoze** [comment]
I tried adding the css folder from the link directly into my client my client/stylesheets folder and it did not seem to work.

**Comment by rafa93br** [comment]
Please tell me guys if you have an answer... I am also looking for this

**Comment by shactdeveloper** [comment]
The CSS worked fine but the ionic-material package also comes with a js (to apply ink effects, etc) that requires Angular, so it does not work with Meteor =( How to solve this ?

**Comment by lonehacker** [comment]
From the README in the link -

The angular services ionicMaterialInk and ionicMaterialMotion are used to activate animations

You'll probably need to port these out of Angular somehow to use with meteoric

**Comment by juno249** [comment]
that's pretty cool when we can use ionic-material with Meteor. How we can do it?
