### ISSUE TITLE
Static keypad

### ISSUE THREAD

**Issue by c316** [meteoric/meteor-ionic#136]
There are many apps that use a static keypad for entering numbers. This keypad isn't one that appears when you put your cursor in an input, but one that is visible immediately when navigating to a page. I've included a screenshot. Is it possible to use ionic to setup a static (custom) keypad like this? 

![screenshot_2014-10-22-15-39-21 1](https://cloud.githubusercontent.com/assets/3142974/6995466/8e6c89a4-db10-11e4-836e-1f7aab88ed56.png)

**Comment by nickw** [comment]
Yes, it is possible, but neither Ionic or Meteoric offer anything in the way of help. You'll just have to write your own custom component with your own custom JS and CSS.
