### ISSUE TITLE
Triggering a modal using an {{> ionTab }} element

### ISSUE THREAD

**Issue by enrq** [meteoric/meteor-ionic#137]
Hi everyone. I have been trying to call a modal using one `ionTab` element with a tag `data-ion-modal` but it does not work. Any ideas?

Reading in the ionic forum, I found someone suggesting to use `ng-click="openModal()"`, but I am not sure how to translate this into meteor.

Thanks a lot in advance.

**Comment by nickw** [comment]
I think you can just pass a custom class to the `ionTab`:

```
{{> ionTab class="my-tab"}}
```


And then attach an event handler in your template like normal:

```
'click .my-custom-tab': function(event, template) {
}
```

**Comment by enrq** [comment]
Thanks for the reply Nick, will give it a try later!

**Comment by ecuanaso** [comment]
Hey nickw, what goes inside the click event to actually open up the modal? 
This is only what you have...
'click .my-custom-tab': function(event, template) {
}

**Comment by nickw** [comment]
You will want to open the modal using this method: https://github.com/meteoric/meteor-ionic/blob/master/components/ionModal/ionModal.js#L11

**Comment by ecuanaso** [comment]
Ok thanks for the reply. Here's what I have, I changed the templateName into 'profile'. I'm trying to open a   profile template inside the modal. However it didn't work.

Template.ionTabs.events({
	'click .profile-modal' : function(profile, data){
	    this.template = Template[profile];
	    var view = Blaze.renderWithData(this.template, data, $('.ionic-body').get(0));

	    if (!this.view[profile]) {
	      this.view[profile] = [view];
	    } else {
	      this.view[profile].push(view);
	    }

	    this.views.push(profile);

	    var $modalBackdrop = $(view.firstNode());

	    if (this.views.length === 1) {
	      $modalBackdrop.addClass('active');
	    }

	    var $modalEl = $modalBackdrop.find('.modal').eq(0);
	    $modalEl.addClass(this.enterClasses.join(' '));

	    $modalEl.on(this.transitionEndEvent, function () {
	      $('body').addClass('modal-open');
	      $modalEl.removeClass(this.enterClasses.join(' ')).removeClass(this.enterActiveClass).off('webkitAnimationEnd');
	    }.bind(this));

	    Meteor.setTimeout(function () {
	      $modalEl.addClass(this.enterActiveClass);
	    }.bind(this), 10);
	}	
});

**Comment by ecuanaso** [comment]
Anybody out there that can identify what I'm doing wrong in my code? Thanks

**Comment by nickw** [comment]
@ecuanaso I'm not exactly sure what you're trying to accomplish, but I'm pretty sure you don't need any of this code:

```
this.template = Template[profile];
    var view = Blaze.renderWithData(this.template, data, $('.ionic-body').get(0));

    if (!this.view[profile]) {
      this.view[profile] = [view];
    } else {
      this.view[profile].push(view);
    }

    this.views.push(profile);

    var $modalBackdrop = $(view.firstNode());

    if (this.views.length === 1) {
      $modalBackdrop.addClass('active');
    }

    var $modalEl = $modalBackdrop.find('.modal').eq(0);
    $modalEl.addClass(this.enterClasses.join(' '));

    $modalEl.on(this.transitionEndEvent, function () {
      $('body').addClass('modal-open');
      $modalEl.removeClass(this.enterClasses.join(' ')).removeClass(this.enterActiveClass).off('webkitAnimationEnd');
    }.bind(this));

    Meteor.setTimeout(function () {
      $modalEl.addClass(this.enterActiveClass);
    }.bind(this), 10);
```

It should be as simple as:
```
Template.ionTabs.events({
  'click .profile-modal' : function(profile, data){
    IonModal.open('nameOfExistingTemplate');
  }
});
```

**Comment by ecuanaso** [comment]
Ok what you just posted worked for me. Thanks alot!
