### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by nickw** [meteoric/meteor-ionic#14]
Ionic is licensed under MIT.
The `meteor-ionic` repo doesn't contain any Ionic code, but https://github.com/meteoric/ionic-sass and https://github.com/meteoric/ionicons-sass do.

We are currently bundling https://github.com/jakiestfu/Snap.js/ which is MIT
We plan on bundling https://github.com/hammerjs/hammer.js which is also MIT

Are we allowed to bundle these libraries together? Can we also use the MIT license?

**Comment by Slava** [comment]
As far as I understand you can license your work under MIT and you should mention the libraries you use in your LICENSE file.

**Comment by nickw** [comment]
Thanks @Slava
