### ISSUE TITLE
ionList does not have rubber band scrolling

### ISSUE THREAD

**Issue by sferoze** [meteoric/meteor-ionic#140]
I am using the ionList as shown in the example

```
{{#ionView}}
    {{#ionContent}}
      {{#ionList}}
        {{#each contacts}}
          {{#ionItem path="contacts.show" buttonRight=true avatar=true class="item-icon-right"}}
            <img src="{{avatarUrl}}">
            {{name.first}} {{name.last}}
            {{> ionIcon icon="ios-arrow-forward" class="positive"}}
          {{/ionItem}}
        {{/each}}
      {{/ionList}}
    {{/ionContent}}
  {{/ionView}}
```
Compare 

http://meteoric-contacts.meteor.com/

with the list on the ionic site:

http://ionicframework.com/docs/api/directive/ionList/

The list bounces back when you scroll to the top

Can we get rubber band scrolling with ionList?

**Comment by nickw** [comment]
It has rubber band scrolling when running on the device, it's not needed or desirable on the desktop.

**Comment by sferoze** [comment]
Ah this is true, rubber band scrolling works on the device. thank you.
