### ISSUE TITLE
no difference between headerButtonLeft or headerButtonRight

### ISSUE THREAD

**Issue by sferoze** [meteoric/meteor-ionic#142]
I am trying to add a button to the navbar. 

I am using the code in the template:

```
{{#contentFor "headerButtonRight"}}
    <a href='#'> <i class="ion-ios-loop-strong"></i> </a>
{{/contentFor}}
```

and the button still shows on the left hand side

when I try

```
{{#contentFor "headerButtonLeft"}}
    <a href='#'> <i class="ion-ios-loop-strong"></i> </a>
{{/contentFor}}
```

the button is still on the left hand side.

**Comment by sircharleswatson** [comment]
I had this issue too just now. I had to give my <a> tag the `button` class and then it moved back to the right side

**Comment by sferoze** [comment]
I got it to work with slightly different syntax. 

Here is what worked:

```
{{#contentFor "headerButtonRight"}}
    <button class="button button-clear" data-ion-modal="_contactsNew">{{> ionIcon icon="ios-loop-strong"}}</button>
  {{/contentFor}}
```

**Comment by sircharleswatson** [comment]
@sferoze glad you got it! i think it was just the button class that was important. I needed to use pathFor on mine which is why I used the anchor tag.
