### ISSUE TITLE
How to set custom animation on modal?

### ISSUE THREAD

**Issue by sferoze** [meteoric/meteor-ionic#144]
I need a modal that is fullscreen and slides in from bottom likes this:

http://codepen.io/ionic/pen/gblny

Basically setting the animation of the modal to 'slide-in-up' should work but how?

**Comment by sferoze** [comment]
actually i need to test on the device. I bet it slides up like normal on the device

**Comment by sferoze** [comment]
it works as expected in the simulator

**Comment by vinodb2806** [comment]
Hello,
I want to add some animation or speed time in IonModai.open('templateName'); so please suggest me here.

Thanks in advance.
