### ISSUE TITLE
Ion Scroll event.

### ISSUE THREAD

**Issue by AlexFrazer** [meteoric/meteor-ionic#145]
I want to listen to a scroll event on the `ion-content`. Eg,

```
Template.orderList.onRendered(function() {
  document.addEventListener('scroll', function() {
    // not important
  })
});
```
However it seems ion content has some kind of "special" scroll event. Is that included on this package?

**Comment by nickw** [comment]
The scrolling is handled using [this CSS](https://github.com/meteoric/ionic-sass/blob/master/stylesheets/_scaffolding.scss#L284) on an `.overflow-scroll` element. There's no special scrolling functionality, so you should be able to listen to the even normally.

**Comment by AlexFrazer** [comment]
ah, sorry bout that, just got it to work using that.

**Comment by rohanray** [comment]
As of today, use [this link](https://github.com/meteoric/ionic-sass/blob/master/stylesheets/_scaffolding.scss#L184) .
