### ISSUE TITLE
ionSlideBox destroyed callback

### ISSUE THREAD

**Issue by guilhermedecampo** [meteoric/meteor-ionic#146]
Hi @nickw!

Why we need this unslick on ionSlideBox destroyed callback?

https://github.com/meteoric/meteor-ionic/blob/ff882994ca1bc5f93b0119c6e6f3e7b870c96dd0/components/ionSlideBox/ionSlideBox.js#L30

It give me errors because maybe this element `$('.ion-slide-box')` does not exists at this point.

Also it's a little bit ugly see all the images of ionSlideBox when you change screens.

**Comment by nickw** [comment]
Hmm maybe we don't. Maybe there could be memory leaks though if we keep re-initializing the plugin?

**Comment by guilhermedecampo** [comment]
Don't know @nickw about the memory leaks.

But maybe we can just check if the element indeed there?

I can make a pull request! ;)

**Comment by nickw** [comment]
Sounds good, PRs are always welcome!

**Comment by guilhermedecampo** [comment]
Hey @nickw, in the end I was using it wrong :disappointed:

I don't receive the error anymore. 

But is still ugly see the images being in a list in the transition.

Will try to find a solution for that.

Do you have a clue?

**Comment by nickw** [comment]
> But is still ugly see the images being in a list in the transition.

I'm not sure exactly what you mean by this, but I assume it's a FOUC type situation? In that case maybe you just need to add a preloader to that route?
