### ISSUE TITLE
Remove Header

### ISSUE THREAD

**Issue by odesey** [meteoric/meteor-ionic#148]
I created a test project based on the all components demo:
http://meteor-ionic.meteor.com/

I would like to create a SlideBox page that does not have the header present, how can I do this?

In the `latout.html` I removed everything other than:

    {{#ionBody}}
      {{>yield}}
    {{/ionBody}}

And in the `slideBox.html` template I have:

    <template name="slideBox">
      {{#ionView}}
        {{#ionContent}}
          {{#ionSlideBox}}
            {{#ionSlide class="light-bg"}}
          <h3>Slide 1</h3>
        {{/ionSlide}}
        {{#ionSlide class="dark-bg"}}
          <h3>Slide 2</h3>
        {{/ionSlide}}
        {{#ionSlide class="positive-bg"}}
          <h3>Slide 3</h3>
        {{/ionSlide}}
      {{/ionSlideBox}}
    {{/ionContent}}
    {{/ionView}}
    </template>

But the space for the header is still there. Any way to remove the space for the heading all together?

Thanks.

**Comment by Anwain** [comment]
+1 same problem here

**Comment by jamielob** [comment]
If you add a no-header class to your ionContent, this should remove the space for you.
For example: 
`{{#ionContent class="no-header"}}`
