### ISSUE TITLE
Template refactor?

### ISSUE THREAD

**Issue by rclai** [meteoric/meteor-ionic#15]
I noticed that there's a lot of templates with 

```
<div class="{{classes}}">
    {{> UI.contentBlock}}
</div>
```

I feel like there's gotta be a way to consolidate them somehow maybe?

**Comment by nickw** [comment]
Possibly, but it might make things harder to maintain / understand. I'm fine with leaving it as-is for now, but feel free to suggest some solutions.

**Comment by benstr** [comment]
I agree with @nickw as a general template we should keep things as simple as possible so more people can adopt and maintain it.

**Comment by rclai** [comment]
No problem.
