### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by c316** [meteoric/meteor-ionic#154]
While you are writing your app how do you see console.log outputs? 

Thanks

**Comment by nickw** [comment]
I assume you mean while testing on the device or simulator? If so, there are remote debugging options for both [iOS](http://moduscreate.com/enable-remote-web-inspector-in-ios-6/) and [Android](https://developer.chrome.com/devtools/docs/remote-debugging)

**Comment by c316** [comment]
Thanks, that is what I was looking for.
