### ISSUE TITLE
ionTab with a Specific href

### ISSUE THREAD

**Issue by vertangelx** [meteoric/meteor-ionic#156]
Is it possible to create am `ionTab` with specific url such as `/article/001`?

The following code creates the ionTab without any `href`...

     {{> ionTab title="Article" path="/article/001" iconOff="ios-albums-outline" iconOn="ios-albums"}}

**Comment by nickw** [comment]
Yes, you can pass `href` instead of `path`: https://github.com/meteoric/meteor-ionic/blob/master/components/ionTab/ionTab.js#L26

**Comment by austingayler** [comment]
is there a reason for this? it's only ever documented that the link should be set via "path"
