### ISSUE TITLE
Trying to put android tab-bar in bottom, i cannot find the doc where you set the config.

### ISSUE THREAD

**Issue by DenLilleMand** [meteoric/meteor-ionic#157]
the following code:

        {{#ionTabs style="ios" class="tabs-background-positive tabs-color-light"}}
            {{> ionTab title="Tab1" path="login" icon="android-home"}}
            {{> ionTab title="Tab2" path="home" icon="android-star"}}
            {{> ionTab title="Tab3" path="notifications" icon="heart"}}
            {{> ionTab title="Tab4" path="calendar" icon="gear-b"}}
            {{> ionTab title="Tab5" path="settings" icon="gear-b"}}
      {{/ionTabs}}

puts it in the buttom, while 

          {{#ionTabs style="android" class="tabs-background-positive tabs-color- light"}}
            {{> ionTab title="Tab1" path="login" icon="android-home"}}
            {{> ionTab title="Tab2" path="home" icon="android-star"}}
            {{> ionTab title="Tab3" path="notifications" icon="heart"}}
            {{> ionTab title="Tab4" path="calendar" icon="gear-b"}}
            {{> ionTab title="Tab5" path="settings" icon="gear-b"}}
      {{/ionTabs}}

puts it in the top.   ive tried the following:

     Template.main.rendered = function () {
            $ionicConfigProvider.tabs.position('bottom'); //other values: top
      };

To set settings, but obviously $ionicConfigProvider is undefined,
so i guess my question is, how do i set ionics config settings from meteor?, i only found examples of setting the config with angular. 

I suppose that i can use the ios style, for my android app, but thats 
not really a valid solution in my case.

Btw. ive tried to run it on a live android-device aswell, and its the same result, as in the browser. 

I allso tried to run the demos from the site, on my own mobile-device, with the exact same result.

**Comment by nickw** [comment]
The `style="android"` is what is putting them on the top. I don't think it's currently possible to put android style tabs on the bottom in meteor-ionic, I think from a design/UX perspective that would be potentially confusing to Android users anyway.
