### ISSUE TITLE
No such template: ionNavBar

### ISSUE THREAD

**Issue by maabed** [meteoric/meteor-ionic#16]
Thanks for a great package,

After deploy to modulus.io i got this error `Uncaught Error: No such template: ionNavBar`
Working very well on localhost ,

**Comment by maabed** [comment]
@nickw Works fine when deploy using with debug option in both modules.io or meteor.com servers
`meteor deploy xxx.meteor.com --debug`
Any advice?

**Comment by nickw** [comment]
Hmm that's strange, no idea what that would be. What does the `--debug` option do exactly? What version of the package is getting installed on Modulus?

**Comment by maabed** [comment]
Yes its really strange,  the debug flag don't minify the app files and the package version is 0.1.7

**Comment by nickw** [comment]
@maabed any luck with this? I deployed my first meteor-ionic app to Modulus last night and didn't experience this.

**Comment by umairsiddique** [comment]
I'm also experiencing it on my local development project.

**Comment by nickw** [comment]
Hmm, what version is specified in your `.meteor/versions` file?

**Comment by umairsiddique** [comment]
Wow. For some reason it was stuck at 0.1.0. I added the package hardly an hour ago. I upgraded it to 0.1.11 by running "meteor update meteoric:ionic" and it's working fine. Thanks a lot.
