### ISSUE TITLE
ViewPort seems to be  a little too big, on my device im able to scroll a little to the right. 

### ISSUE THREAD

**Issue by DenLilleMand** [meteoric/meteor-ionic#160]
Hey, so i tried to use the http://ionicframework.com/docs/api/directive/ionContent/  documentation,
to do something like this:
 {{#ionContent scrollbar-x=false has-bouncing=false direction=y}}

and the only thing that seems to work is :
{{#ionContent scroll=false}}
This disables my vertical scroll though, so  im not interested in this. Is there just not any support for 
this yet? or am i doing it wrong?

Thanks.

ps. awesome library! :)

**Comment by nickw** [comment]
Only a few of the `ionContent` options have been implemented at this time. You can see all of them in the source code: https://github.com/meteoric/meteor-ionic/blob/master/components/ionContent/ionContent.js.

As for why your viewport is too large, I'm not sure, I've never experienced that myself. Perhaps something inside the viewport has a large fixed width?
