### ISSUE TITLE
iron router dependency level

### ISSUE THREAD

**Issue by richpowell** [meteoric/meteor-ionic#161]
How dependent is meteoric with iron router?  I'm going to give flow router a shot. https://github.com/meteorhacks/flow-router
Is there any forseeable major conflict with trying this instead of iron-router?
Thanks!

**Comment by nickw** [comment]
Unfortunately it's heavily dependent on `iron:router` - or more specifically `iron:layout`. We make heavy use of `contentFor` regions. I would like to remove this dependency, so I'm open to a PR.
