### ISSUE TITLE
change import paths for scss

### ISSUE THREAD

**Issue by dcsan** [meteoric/meteor-ionic#165]
the scss bug where the files are not found after a meteor reset got this comment:
https://github.com/meteoric/meteorhunt/issues/10#issuecomment-94344255

not sure if this is accurate, but reposting here in case we can avoid that 

----

The import paths are wrong. If you navigate to the .meteor/.../ directory, the scss files start with _. Replace your imports with the following and it should work.

@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/_ionic';
@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/_ionicons';

**Comment by nabiltntn** [comment]
you have to add manually these packages :
fourseven:scss
meteoric:ionic-sass
meteoric:ionicons-sass

**Comment by nickw** [comment]
Yes, this is a known issue with Meteor that will be solved in an upcoming update.
