### ISSUE TITLE
SCSS import paths when building

### ISSUE THREAD

**Issue by srounce** [meteoric/meteor-ionic#166]
How does one use Meteoric with CI?
Been having problems running `meteor build` relating to this:
> Note: On an initial build, i.e. after a fresh meteor reset, importing sass files from packages will throw an error, because the .meteor/local/ directory doesn't exist yet.
(https://github.com/fourseven/meteor-scss#includepaths)

**Comment by tmikoss** [comment]
The only option known to me would be to pre-launch meteor as part of your build script (see the part about `BUILDPACK_PRELAUNCH_METEOR` in https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile ). But in my experience this process is slow and prone to random failures :/

I've taken to simply pre-compiling the SCSS files to CSS on dev machine and checking those into source control. If you have https://rubygems.org/gems/sass/ installed and are not customising the SCSS variables:

```
sass ./.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/_ionic.scss > ./client/stylesheets/_ionic.css
sass ./.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/_ionicons.scss > ./client/stylesheets/_ionicons.css
rm -r ./.sass-cache
```

Still, eagerly awaiting a proper solution!

**Comment by nabiltntn** [comment]
you have to add manually these packages :
fourseven:scss
meteoric:ionic-sass
meteoric:ionicons-sass

**Comment by srounce** [comment]
@nabiltntn I think you have misunderstood.

**Comment by AlexFrazer** [comment]
I have the same problem, usually have to restart it a few times and it works.

**Comment by caio-ribeiro-pereira** [comment]
I had a similar issue but with a differente context, in my case I needed to setup Codeship CI and I couldn't because sass was not importing the ionic stylesheet. So I create a little workaround to avoid sass compilation during the CI, I just remove all stylesheets before run the test, running this command:

``` bash
bash -c "rm client/stylesheets/application.scss" && meteor --test --once
```

**Comment by nickw** [comment]
This is a known issue with Meteor that will be solved in an upcoming update.
