### ISSUE TITLE
Number Input on iOS

### ISSUE THREAD

**Issue by athenawisdoms** [meteoric/meteor-ionic#168]
How can a number keypad be shown when a user clicks on a text input that requires only numbers to be filled in?

**Comment by arekom** [comment]
Hi @athenawisdoms  you can try to do ``<input type="text" pattern="\d*">``. This will cause numeric keyboard to show up.

**Comment by nickw** [comment]
Actually I think you just need to use an HTML5 number input: `<input type="number">`
