### ISSUE TITLE
How are you doing email verification?

### ISSUE THREAD

**Issue by c316** [meteoric/meteor-ionic#171]
Since the email verify link will go to the web link how are you doing the verification and keeping the user in the app?

**Comment by c316** [comment]
I'm trying to use deeplinking and the https://github.com/EddyVerbruggen/Custom-URL-scheme cordova plugin to get my app to recognize the deeplink domain. Something like

```
mygreatapp://path?query_string
```

However, the only thing that is happening is that the app is being launched, from there I'm not sure how to get the app to connect the path and query string to the correct route. 

Anyone have any insight that might help?

**Comment by woniesong92** [comment]
+1 I am also curious about email verification flow

**Comment by nickw** [comment]
Sorry, I think this is outside the scope of meteoric.
