### ISSUE TITLE
Disable dragging on the side menu

### ISSUE THREAD

**Issue by Tarang** [meteoric/meteor-ionic#172]
`dragContent` is not able to disable dragging on the side menu

On an ios device the behaviour seems to be a bit different than in chrome where the menu can't be dragged. If the side menu is opened the side menu itself can be dragged like in this screenshot:

![img_1297](https://cloud.githubusercontent.com/assets/1616628/7338583/669cff48-ec50-11e4-94fd-915e88c26a3d.PNG)

Is there a way to prevent this and still have the teal part and under in the screenshot draggable?

Note: White isn't the best background but the menu above is displaced. The screenshot is a full screen shot and not half way - Incase the white background causes confusion.

**Comment by anderson916** [comment]
I have the same question. It is better to disable dragging of the side menu div.

**Comment by xpluscal** [comment]
+1

**Comment by nickw** [comment]
I believe this is the same issue: https://github.com/meteoric/meteor-ionic/issues/50

**Comment by nskoro** [comment]
Anyone have a solution for disabling drag content?
