### ISSUE TITLE
How to publish and retrieve images in meteor-ionic app?

### ISSUE THREAD

**Issue by kaushik1979** [meteoric/meteor-ionic#174]
Were you guys able to integrate following libraries with meteor-ionic?

cfs:filesystem                      0.1.2  Filesystem storage adapter for CollectionFS
cfs:graphicsmagick                  0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:gridfs                          0.0.33  GridFS storage adapter for CollectionFS
cfs:standard-packages

Here is what I am trying - 

Run my meteor-ionic server on localhost:3000
Run meteor-web solution on localhost:5000
App at 3000 connect to the DB of app running at 5000.

While my other publish subscribe works just fine in this model, I dont get any images back.

**Comment by rlech** [comment]
add

    meteor add cfs:standard-packages
    meteor add cfs:gridfs

declare collection
    var imageStore = new FS.Store.GridFS("images");

    Images = new FS.Collection("images", {
      stores: [imageStore]
    });


template.html
    <input type="file" name="..." class="upload">


    Template.Profile.events({
      'change .upload': function(event, template) {
        FS.Utility.eachFile(event, function(file) {
          Images.insert(file, function (err, fileObj) {
            if (err){
                 ...
            } else {
              var userId = Meteor.userId();
              var imagesURL = {
                "profile.image": "/cfs/files/images/" + fileObj._id
              };
              Meteor.users.update(userId, {$set: imagesURL});
            }
          });
        });
      }
)};

publish collection via

    Meteor.publish("images", function(){
      return Images.find();
    });


iron:router code

    Router.route('/profile',{
      waitOn: function () {
        return Meteor.subscribe('images')
      },
      action: function () {
        if (this.ready())
          this.render('Profile');
        else
          this.render('Loading');
      }
    });


in template get image via

    <img src="{{currentUser.profile.image}}">





also note that bug, its not working on mobile devices (ios/android) so you have to download the stuff from the client. no idea how to fix this.: https://github.com/CollectionFS/Meteor-CollectionFS/issues/425#issuecomment-105708992
