### ISSUE TITLE
SlideBox Callback?

### ISSUE THREAD

**Issue by odesey** [meteoric/meteor-ionic#175]
How can I execute some code after each slide in the slidebox example? I've looked at the documentation and don't even see the slidebox included in it.

Great work by the way!

Thanks.

**Comment by nickw** [comment]
We're using Slick.js, you might want to take a look at their docs: https://github.com/kenwheeler/slick/

**Comment by odesey** [comment]
Thanks, I will research and share my findings here.

**Comment by odesey** [comment]
Ok I figured this out.

In order to add a callback to the slideBox slides do the following:

     Template.slideBox.onRendered(function () {
	  $('.ion-slide-box').on('swipe', function(event, slick, direction){
	    console.log(direction);
	  });

	  $('.ion-slide-box').on('beforeChange', function(event, slick, currentSlide, nextSlide){
	    console.log(nextSlide);
	   });
     }) 

You can also call:

    $('.ion-slide-box').slick('slickCurrentSlide') //current slide index, great for showing and hiding links

and

      $('.ion-slide-box').slick('slickPrev') // previous slide
      $('.ion-slide-box').slick('slickNext') //next slide


Can we update to documentation and add this to it?

Thanks for pointing me in the right direction.

**Comment by harryward** [comment]
Thanks that seemed to work for me.. using dynamic data and offsetting the 'contact' you are viewing based on what slide your on.

http://xvolve.meteor.com/
