### ISSUE TITLE
Tabs: activate current tab on page load

### ISSUE THREAD

**Issue by nickw** [meteoric/meteor-ionic#18]
As reported by @benstr in https://github.com/meteoric/meteorhunt/issues/3

How do we set the current tab when the page first loads?

Currently the current tab is set when a tab is clicked: https://github.com/meteoric/meteor-ionic/blob/master/components/ionTab/ionTab.js#L2

**Comment by nickw** [comment]
Here's a graphic that explains why we can't rely on URLs to set the current tab but instead have to use a Session variable. Notice that active tab for each of the routes:
![tabs-ui](https://cloud.githubusercontent.com/assets/3907/5689841/48e1c546-9823-11e4-98d3-4129826fbea8.png)

**Comment by davidwoody** [comment]
Something like this should work - https://github.com/meteoric/meteor-ionic/commit/093ae320f874c9ddd7867048a299b05a5df83559

**Comment by benstr** [comment]
In my Meteor projects (mostly enterprise, SEO is not an issue) I have three guidelines on this subject. 

1. All parameters need to be passed as a query.
2. If a parameter needs to be baked into the route then the parameter must always take a "sub-level" position, as opposed to a "top-level" position when compared with other routes on the same level..

  **Wrong:** `products/123`
  **Correct:** `products/details/123`
3. Any route related Sessions are set in IR **action:**
