### ISSUE TITLE
making room for ads #116

### ISSUE THREAD

**Issue by richpowell** [meteoric/meteor-ionic#185]
I've implemented ads but its overridding the TABS at the bottom.  Ad's have different sizes based on differerent devices. the iphone banner ads are 50px, on other devices it maybe larger.  I need to figure out how to push up the tabs based on the height of the ad, which is dependent on the device and platform. 
I tried manually overidding the bottom property as suggested in the issue from #116 but I couldnt figure that out.  But I will also see challeges if I hard code a value.  Any suggestions on how to override this value? I can hard code different values for different devices in a @media {}..

**Comment by richpowell** [comment]
So after a bit of hacking. If I include this in my app.scss file I get a area for ads to show in the bottom.
body, .ionic-body{
   position:absolute;
    margin-bottom:25px;
}
However, when clicking on the tab icon and going to the that tabs screen, the tab at bottom is off a bit in its shift. and I notice that its down a few more pixels that the main view.  Is there something different in the tabs vs tab main view(i think i saw nick mention this somewhere in the code)?

Im 99% sure I can customize the views for different apps by breaking this out into different
@media screen for the various devices. 

My code follows the tabs demo..

**Comment by lj222kj** [comment]
Hey!

Did you come up with a good way to place ads? Am looking into integrating ads myself in one of my meteoric apps but i'm not entirely sure how to solve it.

**Comment by richpowell** [comment]
I added a custom css file. and used the styling below.  Then I added admob as a bottom banner.
Heres the main template also. So you can see where I added the id to which elements.  Not sure about the TAB view its been a while since I played with this. 

<template name="main">

{{#ionHeaderBar class="bar bar-header bar-assertive"}} 
<h1 class="title">SALEZY</h1>
<div class="buttons">	
<button class="popup-buttons button button-assertive" id="popover" data-ion-popover="popover" >					{{> ionIcon icon='more'}}	</button>
 </div>
{{/ionHeaderBar}}

{{#ionContent class="calm"}}
<div class="row">
	<div align ="center" class="col">
<h2 class="styling">{{content}}</h2>
</div>
</div>

{{/ionContent}}
{{#ionFooterBar}}
<div id ="adpadding" class="row bar bar-footer calm  buttons">
<button id="quote" class="col col-33 col-offset-33 button button-assertive " >Press Me</button>
</div>
{{/ionFooterBar}}
</template>


/* iPhone Portrait */
@media screen and (max-device-width: 480px) and (orientation:portrait) {
#adpadding{
	bottom:50px;
	height:60px;
}
} 

/* iPhone Landscape */
@media screen and (max-device-width: 480px) and (orientation:landscape) {
#adpadding{
	bottom:50px;
	height:60px;
}
}

/* iPad Portrait */
@media screen and (min-device-width: 481px) and (orientation:portrait) {
#adpadding{
	bottom:90px;
	height:60px;
}
}

/* iPad Landscape */
@media screen and (min-device-width: 481px) and (orientation:landscape) {
#adpadding{
	bottom:90px;
	height:60px;
}
}
