### ISSUE TITLE
ionTab badgeNumber attribute how to support the variable ？ 

### ISSUE THREAD

**Issue by zhongboqing** [meteoric/meteor-ionic#188]
ionTab badgeNumber attribute how to support the variable，for example：
{{#ionTabs class="tabs-positive tabs-icon-top"}}
  {{> ionTab title="News" badgeNumber=“{{newsCount}}” path="news" iconOff="ios-paper" iconOn="ios-paper"}}
  {{> ionTab title="Todos" badgeNumber=“{{todosCount}}” path="todos" iconOff="checkmark-circled" iconOn="checkmark-circled"}}
  {{> ionTab title="Profile" path="profile" iconOff="person" iconOn="person"}}
{{/ionTabs}}

**Comment by kevingzhang** [comment]
newCount is variable.
In your js code, using Template.yourTemplateName.helpers to set newsCount to a value.
