### ISSUE TITLE
Page transition animation when going to page with tabs

### ISSUE THREAD

**Issue by odesey** [meteoric/meteor-ionic#190]
When navigating to a page that has Tabs, there is no page transition animation. I know that while navigating tabs that the page transition is disabled but how can I enable the sliding transition when entering and leaving a page with Tabs?

**Comment by nickw** [comment]
I think you can just set this to `false`: https://github.com/meteoric/meteor-ionic/blob/master/components/ionTab/ionTab.js#L9
