### ISSUE TITLE
jQuery + Meteoric??

### ISSUE THREAD

**Issue by markclayton** [meteoric/meteor-ionic#191]
Hey guys quick question. It may just be my project, but it seems that jQuery does not work when ```meteoric:ionic``` is installed. I've noticed that whenever I attempt to do something like the following:

```var x = $("#my-id").val();```

The value ```x``` is simply not obtained as it generally would. I have the ```jquery``` package installed as well. It just doesn't seem to work. In addition, I was hoping to use the ```bjimdar:datedropper``` as well, however due to it's usage of jQuery in the following code taken from https://atmospherejs.com/bjimdar/datedropper:

```
var options = {           
    format:"m/d/Y",                     
    placeholder: "choose date...",
  };

  $( ".date-field-selector" ).dateDropper(options);
```
I am unable to get it to work. I believe there is an overall issue with jQuery + Meteoric. I could just be missing something. I am fairly new to Meteor. 

Any help is appreciated.

**Comment by nickw** [comment]
There shouldn't be any issues with Meteoric+jQuery, Meteoric makes extensive use of jQuery internally.

**Comment by timbrandin** [comment]
I don't even think you need to include the jquery package these days, I mostly use jquery stuff from the instance like this:
```
Template.tpl.events({
  'click .btn': function(event, instance) {
    instance.$('.class').toggleClass('active');
  }
});
```

Template.tpl.helpers({
  helper: function() {
    var instance = Template.instance();
    instance.$('.class').addClass('active');
  }
});

**Comment by markclayton** [comment]
Ah that's very relieving. Thanks nickw and timbrandln for clearing this up for me. I'm still fairly new to meteor and absolutely love it. Once again thanks guys.
