### ISSUE TITLE
Ionic View

### ISSUE THREAD

**Issue by Praxie** [meteoric/meteor-ionic#192]
Hi. Is it possible to share the app via Ionic View? http://view.ionic.io/

**Comment by nickw** [comment]
Not sure, I would need to see some docs on how Ionic View works internally.

**Comment by rlech** [comment]
why not using testflight?

**Comment by joshua1** [comment]
@nickw this will be really nice to have. were you able to check this. Thanks

**Comment by lj222kj** [comment]
Has this issue been addressed yet?

**Comment by nickw** [comment]
I'm assuming this feature requires bundling an angular-ionic app to Ionic's servers - so probably not possible with Meteor.
