### ISSUE TITLE
Changing page transitions?

### ISSUE THREAD

**Issue by AlexFrazer** [meteoric/meteor-ionic#193]
Is it possible to change page transitions?

I want certain routes to slide up, while others do the default transition

If so, can documentation be added for how to change the page transition?

**Comment by nickw** [comment]
You _should_ be able to pass an animation name to your `ionNavView` as you can see [in the source](https://github.com/meteoric/meteor-ionic/blob/master/components/ionNavView/ionNavView.js#L15). The animations you can use are in the sass: [_animations.scss](https://github.com/meteoric/ionic-sass/blob/master/stylesheets/_animations.scss).

```
{{#ionNavView animation="slide-in-up"}}
{{/ionNavView}}
```

**Comment by dcsan** [comment]
@AlexFrazer did you get this working nicely? i'm trying to disentangle the angular stuff from the ionic docs to have a clear way to try other transitions
http://ionicframework.com/docs/api/directive/ionNavView/

should ionNavView be used instead of a plain ionView ?
and the transition is added on the target view you are transitioning to?

**Comment by adamsidiali** [comment]
Looks like it changed, I got it working by doing `transition="slide-in-up"`

**Comment by gfmr90** [comment]
Hey @adamsidiali, could you drop more tips on how you get it working? I'm new in Meteoric development and I can't still seem to figure out how transitions work. Am I suppose to configure anything?

**Comment by gottib** [comment]
Hi @adamsidiali and @gfmr90 , can one of you drop some more detailed information about customizing or configuring on transitions? I would really appreciate this.

**Comment by gottib** [comment]
I got it:

angular.module('visidoo').config(function($ionicConfigProvider) {
    $ionicConfigProvider.views.transition('none');
});

http://ionicframework.com/docs/api/provider/$ionicConfigProvider/#views.transition
