### ISSUE TITLE
some serious issues with footer and input element inside footer

### ISSUE THREAD

**Issue by avl055** [meteoric/meteor-ionic#195]
I have experienced many issues (spent days on this) with footer element. particularly input box inside footer and "keyboard-attach". i have to say that i have considered dropping ioninc completely several times as this issue is absolutely critical for a chat app. Finally I've tried Angualr version of the same feature - and it just worked (at least no issues so far). I can't believe that there are such inconsistencies. If this project is to succeed, it should be 1-1 consistent wiht "angular" ionic. Otherwise just the amount of support for angular ionic would make people switch. investingating "meteoric" specific issues is almost impossible.

**Comment by nickw** [comment]
Yes this requires a bit of custom CSS. Here's what I've done in the past:

```
.bar-footer {
  .item-input-wrapper {
    background: none;
    padding: 0;
  }

  .button-clear {
    width: 60px;
  }

  .button-block {
    margin: 0;
  }
}
```

```
<div class="bar bar-footer bar-stable has-tabs" data-keyboard-attach>
      <form class="item-input-wrapper form-send-message">
        <input type="text" placeholder="Enter Message…" name="message">
        <button class="button button-positive button-clear" type="submit">Send</button>
      </form>
    </div>
```
