### ISSUE TITLE
Problem by pressing the input

### ISSUE THREAD

**Issue by allanalexandre** [meteoric/meteor-ionic#197]
Guys, I have a problem in the inputs of my interface whenever a field is pressed (active), appears something over everything (Attached photos) .. this happens only qnd generate the (.apk) and ran on the phone, he running on the browser does not nothing happens, therefore believe it is somewhere in the build process mobile, can you help me?

![imgapp](https://cloud.githubusercontent.com/assets/3044907/7726002/9a92f1e4-fed5-11e4-8f44-86effa4030db.jpg)

**Comment by nickw** [comment]
This is most likely related to one of the outstanding Android keyboard bugs e.g. https://github.com/meteoric/meteor-ionic/issues/130

**Comment by LucNaterop** [comment]
Same problem here. Inputs seem to be a big issue... Also got slight problems with inputs on under iOS.

**Comment by sebastianconcept** [comment]
Maybe is `keyboard-attach` related?

I've found this:
http://stackoverflow.com/questions/25328701/ionic-angularjs-phonegap-keyboard-issue-with-ios

And BTW I have this same major issue for iOS =(

**Comment by allanalexandre** [comment]
Check for https://github.com/meteoric/meteor-ionic/issues/130
