### ISSUE TITLE
Ionic 1.0.0

### ISSUE THREAD

**Issue by simongroll** [meteoric/meteor-ionic#198]
Love your work.
Any plans to update Ionic to 1.0.0?

Quite a few features I'm looking forward to, particularly *Swipe to Go Back*.
This would resolve https://github.com/meteoric/meteor-ionic/issues/3.

**Comment by tekknikk** [comment]
+1 on the love

**Comment by pedrocatre** [comment]
+1
(Amazing work btw! Really appreciate it.)

**Comment by AlexFrazer** [comment]
+1

**Comment by cosio55** [comment]
+1

**Comment by jaskinn** [comment]
+1

**Comment by 1nsaneinc** [comment]
+1
Waiting desperately for 1.0.0!

**Comment by rlech** [comment]
+1

**Comment by joshua1** [comment]
@nickw any response?

**Comment by nickw** [comment]
I don't have any plans to attempt a 1.0 upgrade right now. "Swipe to go back" in particular will be quite difficult to implement and will probably require a custom router (or a heavily modified version of an existing router). I'm also much more interested in React and React Native right now, but if my interest returns to Ionic I will definitely look at upgrading.
