### ISSUE TITLE
using side menus

### ISSUE THREAD

**Issue by geritol** [meteoric/meteor-ionic#20]
Hi! just a short question.
How to enable side menu on just one side?
Eg. if i only put left side menu container, the menu will appear on both sides (the rigth one is empty)

**Comment by nickw** [comment]
I'm not sure I understand the question, you should be able to put a menu on only one side like this:

```
{{#ionBody}}
  {{#ionSideMenuContainer}}
    {{#ionSideMenus}}
      {{#ionSideMenu}}
        side menu content
      {{/ionSideMenu}}
    {{/ionSideMenus}}
    {{#ionSideMenuContent}}
      // your apps content, tabs, headers, etc:
      {{> yield}}
    {{/ionSideMenuContent}}
  {{/ionSideMenuContainer}}
{{/ionBody}}
```

Let me know if that doesn't work.

**Comment by geritol** [comment]
Tried your code too, but for me this makes the same thing happen. I have two side menus. My code is prety much the same exept i used {{#ionSideMenu side="left"}}.

**Comment by nickw** [comment]
Can you explain what you mean by "having two side menus"?

**Comment by geritol** [comment]
that both sides are active. 
example (working with drag only) here:
http://meteoric-sidemenu-test.meteor.com/

**Comment by geritol** [comment]
code here:
https://github.com/geritol/meteoric-sidemenu-test

**Comment by nickw** [comment]
Ah I see what you mean. We're using [Snap.js](https://github.com/jakiestfu/Snap.js) under the hood, so I'm not sure if that's just the way it works, or if we have to set a configuration variable, or what. Feel free to take a look at their docs, otherwise I'll take a look in the next few days.

**Comment by jaskinn** [comment]
There seems to be a default setting ('disable: 'none'), that you can set to whichever side you want. ie disable: 'right' - taken from the https://github.com/jakiestfu/Snap.js#settings-and-defaults documentation.

**Comment by dancering** [comment]
Try this:

Template.nameXXX.rendered = function () {
&nbsp;&nbsp;&nbsp;&nbsp;IonSideMenu.snapper.settings({disable: 'right'});
};

It's working for me.

**Comment by geritol** [comment]
Working here too. 
Thanks!

**Comment by nickw** [comment]
Hey guys,
I just added [this commit](https://github.com/meteoric/meteor-ionic/commit/4d3e302c9ec528b6721be344ff68042ada22e1f3) which allows you to pass a `side` option to the `ionSideMenuContainer` component like so:

```
{{#ionSideMenuContainer side="left"}}
```
or
```
{{#ionSideMenuContainer side="right"}}
```
or
```
{{#ionSideMenuContainer side="both"}}
```

and it will take care of disabling the correct side for you.

**Comment by gregheth** [comment]
Thanks for the software update!  Just what I needed.

(I am new to Github. I want to update the Meteoric documentation for this.  Where is the recommended procedure to do this?  A "pull request" I think. )

**Comment by weijian19391** [comment]
Hi all! 
I've tried to disable the side menu on certain templates, but the code `Template.nameXXX.rendered = function () {
    IonSideMenu.snapper.settings({disable: 'right'});
};` is not working for me. Can i know if there's a newer api for doing that?
