### ISSUE TITLE
IonTab not pulling in icons

### ISSUE THREAD

**Issue by Vaqxin** [meteoric/meteor-ionic#207]
When I try to replace the default icons from the guides IonTab code block:

{{#ionTabs class="tabs-positive tabs-icon-top"}}
  {{> ionTab title="News" path="news" iconOff="ios-paper" iconOn="ios-paper"}}
  {{> ionTab title="Todos" path="todos" iconOff="checkmark-circled" iconOn="checkmark-circled"}}
  {{> ionTab title="Profile" path="profile" iconOff="person" iconOn="person"}}
{{/ionTabs}}

TO:

{{#ionTabs class="tabs-positive tabs-icon-top"}}
	  {{> ionTab title="Home" path="home" iconOff="ios-paper" iconOn="ios-paper"}}
	  {{> ionTab title="Send" path="contacts" iconOff="ion-android-send" iconOn="ion-android-send"}}
	  {{> ionTab title="Profile" path="profile" iconOff="person" iconOn="person"}}
 {{/ionTabs}}

The new icon reference "ion-android-send" seems to work since it's pulled into the app. However the icon never loads. If I inspect the html, I see that it is in fact building correctly. 

Any idea what's going on?

**Comment by nickw** [comment]
You don't need the `ion-` part when specifying the icon like this.

**Comment by Vaqxin** [comment]
Totally missed that. I was seriously wondering what the issue was. Updated GUIDE and submitted PR. Thanks!
