### ISSUE TITLE
how to remember the position when back!

### ISSUE THREAD

**Issue by train860** [meteoric/meteor-ionic#209]
Hi,

I have looked the product hunt demo,I found that the list view will pull data from server again where you back from the detail view,and cannot remember the position!

I am wondering if there are some ways to resolve!

thank you!

**Comment by elie222** [comment]
You could use Javascript to find which item is top of the list on screen when the user navigates away from the page, save it as a query in the route and then use it if it exists when the user navigates back to the page.

**Comment by elie222** [comment]
Save it as a query parameter *

**Comment by nickw** [comment]
@train860 this would require some way of caching the data and the template which is currently outside the scope of this project.
