### ISSUE TITLE
meteoric_ionicons-sass not build

### ISSUE THREAD

**Issue by achtan** [meteoric/meteor-ionic#213]
hi in my `.meteor/local/build/programs/server/assets/packages/` i have `meteoric_ionic-sass` but i dont have `meteoric_ionicons-sass` ...
in packages i have following:
...
fourseven:scss
meteoric:ionic-sass
meteoric:ionicons-sass
meteoric:ionic

**Comment by lucavandro** [comment]
Try this 
```sh
meteor remove fourseven:scss
meteor remove meteoric:ionicons-sass

meteor add fourseven:scss@2.0.0
meteor add meteoric:ionic-sass
meteor add meteoric:ionicons-sass
meteor add meteoric:ionic
´´´

**Comment by achtan** [comment]
it helpt! thx
