### ISSUE TITLE
Adding custom icons to the project

### ISSUE THREAD

**Issue by kaushik1979** [meteoric/meteor-ionic#218]
Hi,

I am trying to add custom icons to my project but the icons do not show up.

I added my icon to the mobile-config.js file - 
```
App.icons({
      'qoll_1_100_px': 'resources/img/1_100_px.png',
});
```

Then I put the following the html - 
```
{{> ionIcon icon='qoll_1_100_px'}}
```

Any ideas what am I missing here or not doing right?

**Comment by nickw** [comment]
`App.icons` are for specifying the icon(s) that shows up on a device's homescreen - not the icons within your app's UI. To add addition UI icons you would just need to use CSS as usual.
