### ISSUE TITLE
Can't get list item to link

### ISSUE THREAD

**Issue by t3db0t** [meteoric/meteor-ionic#226]
In the Contacts example, the `ionItem` line is just:
`{{#ionItem path="contacts.show" buttonRight=true avatar=true class="item-icon-right"}}`
And it generates the list items with the _id appended to the path.  I want to do the same thing, but copying this format isn't working for me—what else is needed?  Everything renders correctly, but the listItems are not links.

Here's what I've got:

lib/router.js
```
Router.map(function() {
  this.route('home', {path: '/', layoutTemplate: 'tabsLayout'});
  this.route('star', {path: '/star', layoutTemplate: 'tabsLayout'});
  this.route('heart', {path: '/heart', layoutTemplate: 'tabsLayout'});
  this.route('gear', {path: '/gear', layoutTemplate: 'tabsLayout'});
  this.route('star.detail', {path:'/star/:id', layoutTemplate: 'tabsLayout'});
});
```

client/star.html
```
<template name="star">
  {{#ionView}}

    {{#ionContent class="padding"}}
    	{{#contentFor "headerTitle"}}
		  <h1 class="title">Star</h1>
		{{/contentFor}}

    	{{#ionList}}
	        {{#each listItems}}
	          {{#ionItem path="star.detail" buttonRight=true class="item-icon-right"}}
	          	<h2>{{title}}</h2>
	            <p>{{_id}}</p>
	            {{> ionIcon icon="ios-arrow-right"}}
	          {{/ionItem}}
	        {{/each}}
	    {{/ionList}}
    {{/ionContent}}

    {{> _tabs}}
  {{/ionView}}
</template>

<template name="starDetail">
	<h1>Star Details</h1>
</template>
```

client/base.html
```
<template name="tabsLayout">
	{{#ionBody}}
		{{> ionNavBar class="bar-positive"}}

		{{#ionNavView}}
			{{> yield}}

		{{/ionNavView}}
		{{> _tabs}}
	{{/ionBody}}
</template>

<template name="_tabs">
  {{#if isAndroid}}
    {{#ionTabs style="android" class="tabs-background-positive tabs-color-light"}}
      {{> ionTab title="Home" path="home" icon="android-home"}}
      {{> ionTab title="Star" path="star" icon="android-star"}}
      {{> ionTab title="Heart" path="heart" icon="heart"}}
      {{> ionTab title="Gear" path="gear" icon="gear-b"}}
    {{/ionTabs}}
  {{else}}
    {{#ionTabs style="ios" class="tabs-background-positive tabs-color-light"}}
      {{> ionTab title="Home" path="home" iconOff="ios-home-outline" iconOn="ios-home"}}
      {{> ionTab title="Star" path="star" iconOff="ios-star-outline" iconOn="ios-star"}}
      {{> ionTab title="Heart" path="heart" iconOff="ios-heart-outline" iconOn="ios-heart"}}
      {{> ionTab title="Gear" path="gear" iconOff="ios-gear-outline" iconOn="ios-gear"}}
    {{/ionTabs}}
  {{/if}}
</template>
```

**Comment by t3db0t** [comment]
If you look at my repo (https://github.com/t3db0t/Meteoric-Mobile-Starter-Project) and compare it to the Contacts example, you'll see that they are effectively identical except mine has the tabs in the layout. I even tried adding tabs to the Contacts example and it still worked, of course.

So it seems like my project is somehow missing some kind of core element. The Contacts example has more packages installed, but none of them would seem to be relevant (i.e. zimme:active-route or autoforms).

What gives?

**Comment by nickw** [comment]
It's probably something to do with the way `iron:router` generates routes. What are the `listItems` objects exactly? Check out: https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#path-and-link-template-helpers

**Comment by t3db0t** [comment]
Figured it on on the Meteor forums—the Router path is `/star/:id` when it needed to be `/star/:_id`...
