### ISSUE TITLE
data-action not working for buttons inside nav-bar

### ISSUE THREAD

**Issue by balasivagnanam** [meteoric/meteor-ionic#229]
```
 {{#contentFor "headerButtonRight"}}
    <button class="button button-clear" data-ion-modal="assesmentNew">{{> ionIcon icon="ios-plus-empty"}}</button>
    <button class="button button-clear" data-action="logOut">Logout</button>
  {{/contentFor}}
```

i am having this data-action for the button in nav-bar and it is not invoking the respective event.

```
Template.assesments.events({
  'click [data-action=logOut]': function(event, template) {
      console.log("entered signout");
    Meteor.logout();
    Router.go("/");
  }
});
```

**Comment by yhyuan** [comment]
Hi 
try to change the template name to layout. It seems the layout template is used to render the buttons. 

Template.layout.events({
  'click [data-action=logOut]': function(event, template) {
      console.log("entered signout");
    Meteor.logout();
    Router.go("/");
  }
});

**Comment by nickw** [comment]
That's right, anything inside of `{{#contentFor "headerButtonRight"}}` will be pulled out of your template and injected into the layout, so you'll need to attach events on the layout.

**Comment by codeHatcher** [comment]
Oh man, I just spent a couple hours on this not realizing this was the case.

**Comment by jupiterkenji** [comment]
I renamed it to 'layout' but it doesn't seem to be recognised and I got: Uncaught TypeError: Cannot read property 'events' of undefined. Any clue/s?
