### ISSUE TITLE
Scroll positions - how do they work?

### ISSUE THREAD

**Issue by rjakobsson** [meteoric/meteor-ionic#23]
First: Amazing work! Thank you so much, this is a really useful for me.
In your demo apps, I can see that you've got scroll position working correctly - on "Back" it's on the same place it where when you left the page. Do I need to do anything special to get this behavior?

**Comment by nickw** [comment]
Thanks Robin!

Yes, you should get that functionality "out of the box" with no extra work in the latest version of meteor-ionic. Let me know if that is not the case.
