### ISSUE TITLE
Can I use SQLite in meteor-ionic?

### ISSUE THREAD

**Issue by yokas** [meteoric/meteor-ionic#234]
I'm creating an ios app using ionic and will use sqlite for storage, since I found meteor-ionic, I would like to use meteor-ionic because I love meteor more, my question is can I use SQLite in meteor-ionic? And how?
If not, what database should I use(sqlite like for unlimited local storage)?

**Comment by benjick** [comment]
Why not use mongodb that's shipped with Meteor?

**Comment by yokas** [comment]
Can I use mongodb as a persistent db in ios ?
I'm creating an ios app which needs store data locally

**Comment by nickw** [comment]
@yokas this is a general Meteor question and isn't specifically related to meteoric. A simple Google search for "meteor local storage" returns several useful results, including: https://forums.meteor.com/t/meteor-mobile-app-local-storage/2646
