### ISSUE TITLE
Make android alignments optional?

### ISSUE THREAD

**Issue by rclai** [meteoric/meteor-ionic#24]
I have the following layout:
```
{{#ionBody}}
    {{> ionNavBar class="item-input-inset bar-calm"}}
      
    {{#ionNavView}}
      {{> yield}}
    {{/ionNavView}}
{{/ionBody}}
```

One of my routes has an template that has this:

```
{{#contentFor "headerButtonLeft"}}
    <a href="{{pathFor 'search'}}" class="button icon ion-search"></a>
  {{/contentFor}}
  
  {{#contentFor "headerTitle"}}
    <h1 class="title">Production Orders</h1>
  {{/contentFor}}
  
  {{#contentFor "headerButtonRight"}}
    <button class="button">Put Away</button>
  {{/contentFor}}
```

And as you know, this will render properly on an iOS device, but on an Android, the headerTitle is going to align left, as per this line of code: https://github.com/meteoric/meteor-ionic/blob/master/components/ionHeaderBar/ionHeaderBar.js#L6

Are you guys able to make these platform-based rules optional?

**Comment by nickw** [comment]
Hmm, I'd be open to a PR for this, but I personally don't have a use for this functionality. One of my primary motivations for building meteoric was to be able to build "cross platform UIs" that look appropriate on Android as well as iOS.

**Comment by rclai** [comment]
If a title is always left-aligned, it assumes that Androids don't ever have a top-left button? Or if they do, then there's no title? How would you advise?

**Comment by rclai** [comment]
Oh wait, I guess according to your article here:
https://medium.com/space-camp/cross-platform-uis-for-mobile-meteor-apps-6f12b583b205

Facebook pushes all buttons to the right.

**Comment by nickw** [comment]
> If a title is always left-aligned, it assumes that Androids don't ever have a top-left button? Or if they do, then there's no title? How would you advise?

For now the left button will just show up to the left of the title (like the back buttons do).

> Facebook pushes all buttons to the right. Interesting.
Yeah, I haven't tackled the "all buttons on the right" feature for Android yet. It's on my todo list.

**Comment by rclai** [comment]
Oh you know what I noticed. So when I looked at the android Gmail and maps app, I noticed they have a left aligned menu button and the title is actually aligned left too but right next to the menu button. Check it out.

**Comment by nickw** [comment]
Yeah that's what we're doing now actually, but it seems like it's more common for Android apps to have all the buttons on the right (except for back buttons and hamburger menus).

Here's an app I'm working on right now:

![screen shot 2015-01-18 at 5 58 12 pm](https://cloud.githubusercontent.com/assets/3907/5795061/a3f1a734-9f3b-11e4-920f-633f2ebb0a18.png)

And here's the [Meteor Hunt](http://meteorhunt.meteor.com) app on Android:
![screen shot 2015-01-18 at 5 55 46 pm](https://cloud.githubusercontent.com/assets/3907/5795049/57454882-9f3b-11e4-85a7-b9fc7fd47a25.png)

I think in the Meteor Hunt case, it would be better if the search icon was on the right.
