### ISSUE TITLE
Tab on/off state doesn't react to Router.go

### ISSUE THREAD

**Issue by lorensr** [meteoric/meteor-ionic#242]
Eg if I'm on `news` and call `Router.go 'todos'`. The `todos` route is rendered, but the news icon is still on the `iconOn` version. Note that:

- If I click on `todos` tab icon, it works as expected
- My `#ionTabs` is in an IR layout that is shared between the two routes, and is not rerendered when switching between them.

```
{{#ionTabs class="tabs-positive tabs-icon-top"}}
  {{> ionTab title="News" path="news" iconOff="ios-paper" iconOn="ios-paper"}}
  {{> ionTab title="Todos" path="todos" iconOff="checkmark-circled" iconOn="checkmark-circled"}}
  {{> ionTab title="Profile" path="profile" iconOff="person" iconOn="person"}}
{{/ionTabs}}
```

**Comment by nickw** [comment]
For now you should be able to manually set `Session.set('ionTab.current')`.

**Comment by java99** [comment]
I open a screen with a  navbackbutton:

	{{#contentFor "headerButtonLeft"}}
		{{#if gotolist}}
			{{>ionNavBackButton path='tabs.list' }}
		{{/if}}

on returning from the settings screen with the latter backbutton, the Session.get('ionTab.current') I use to manually set the tab and determine status gets manipulated to "/tabs/list" whereas I need it to be "tabs.list" (iron router path). My browser path is "/tabs/list" but nowhere in my code do I set ionTab.current to other version. I assume it must be set internally when pressing the navbackbutton. 
Can I change this?
