### ISSUE TITLE
Is there a date picker for meteor ionic? 

### ISSUE THREAD

**Issue by yhyuan** [meteoric/meteor-ionic#249]
I found most of them depend on angular.js.

**Comment by timbrandin** [comment]
Would be nice with something extensible! For example the dates could be set in different color depending on some collection data etc.

**Comment by xpluscal** [comment]
+1

**Comment by nickw** [comment]
On a device `<input type="date">` will trigger the native datepicker, which is I believe is why Ionic doesn't include their own. I also don't think we want to include any components in meteoric that aren't in Ionic.
