### ISSUE TITLE
IonItem needs more route options

### ISSUE THREAD

**Issue by benstr** [meteoric/meteor-ionic#25]
Loving Meteoric! When working with *ionItem* I need to tap into IronRouter's features such as query, hash, & data. Chris has a great `href` helper **[pathFor](https://github.com/EventedMind/iron-router/blob/devel/Guide.md#pathfor)**. 

Are you open to a PR on this?

**Comment by nickw** [comment]
Yeah that would be amazing!

**Comment by benstr** [comment]
https://github.com/meteoric/meteor-ionic/pull/26
