### ISSUE TITLE
Modal screen is translucent

### ISSUE THREAD

**Issue by mervynteo** [meteoric/meteor-ionic#255]
<img width="552" alt="screenshot meteoric modal error" src="https://cloud.githubusercontent.com/assets/5101947/8927608/2de1ccee-354b-11e5-8eef-d104d727208b.png">

<b>Below are the packages involved. underscore</b>

>iron:router@1.0.0-rc.1
sacha:spin
audit-argument-checks
accounts-password
accounts-base
ian:accounts-ui-bootstrap-3
twbs:bootstrap
aldeed:template-extension 
useraccounts:core
http
email
meteorhacks:ssr
momentjs:moment
fourseven:scss
meteoric:ionic
meteoric:ionic-sass
meteoric:ionicons-sass
meteoric:autoform-ionic
useraccounts:ionic

I used to have installed the Semantic-UI but i have uninstalled it now. 
Let me know what other codes to post up. 
My scss files does not contain any code that changes the modal behavior.

**Comment by nickw** [comment]
Hi @mervynteo this seems like something specific to your CSS, but feel free to reopen if you are still experiencing this.
