### ISSUE TITLE
Problem with disabling Snapper

### ISSUE THREAD

**Issue by b1rdex** [meteoric/meteor-ionic#256]
Meteor-ionic demo has SlideBox example: http://meteor-ionic.meteor.com/slideBox
If you open that page from this issue, Snapper disabling will not work — sliding will open side menus.

But if you navigated that page from other demo page, http://meteor-ionic.meteor.com/ for example, disabling is working.

The promlem is here: https://github.com/meteoric/demo/blob/master/client/templates/slideBox/slideBox.js#L2 — I think that rendered method is called too early — snapper is not initialized and disabling fails.

**Comment by b1rdex** [comment]
Oh I was right.

```
Exception from Tracker afterFlush function: Cannot read property 'disable' of null
TypeError: Cannot read property 'disable' of null
    at Template.slideBox.rendered (http://meteor-ionic.meteor.com/e6d29bcba1263281831527494bd4ad7b567747ac.js:227:70)
    at null.<anonymous> (http://meteor-ionic.meteor.com/e6d29bcba1263281831527494bd4ad7b567747ac.js:64:31265)
    at http://meteor-ionic.meteor.com/e6d29bcba1263281831527494bd4ad7b567747ac.js:64:17258
    at Object.l._withCurrentView (http://meteor-ionic.meteor.com/e6d29bcba1263281831527494bd4ad7b567747ac.js:64:21048)
    at http://meteor-ionic.meteor.com/e6d29bcba1263281831527494bd4ad7b567747ac.js:64:17226
    at n.flush (http://meteor-ionic.meteor.com/e6d29bcba1263281831527494bd4ad7b567747ac.js:15:2798)
```

Open that page and open js console.

**Comment by b1rdex** [comment]
Quick solution — replace Template.slideBox.rendered with

```javascript
Template.slideBox.rendered = function tryDisableSnapper() {
  if (IonSideMenu.snapper === null) {
    setTimeout(tryDisableSnapper, 100);

  } else {
    IonSideMenu.snapper.disable();
  }
}
```
Hope you will include better solution to slideBox component.

**Comment by xpluscal** [comment]
+1

**Comment by jorjordandan** [comment]
Just needs to wrapped in an afterFlush likely.
  
    Template.slideBox.rendered = function() {
       Tracker.afterFlush(function(){
          IonSideMenu.snapper.disable();
      }
    };
