### ISSUE TITLE
Extra Space in Nav?

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteoric/meteor-ionic#260]
Hello:

This is an amazing package. I'm following your instructions and everything seems to be going smoothly, except I'm getting some phantom space in my navbar in the iOS Simulator (iPhone 6) that I can't diagnose. 

![image](https://cloud.githubusercontent.com/assets/3259022/9045442/2a28c99a-39f1-11e5-8c60-700b8d4ee86e.png)

Here's my view code:
```
<template name="hello">
	{{#contentFor "headerButtonLeft"}}
	  {{>ionNavBackButton}}
	{{/contentFor}}
	
	  {{#contentFor "headerTitle"}}
	    <h1 class="title">Details</h1>
	  {{/contentFor}}

	{{#ionView}}
		{{#ionContent}}
		<h1>Welcome to Ionic!</h1>
		<button>Click Me Please</button>
		{{/ionContent}}
	{{/ionView}}
</template>
```
```
<template name="AppLayout">
{{#ionBody}}
  {{> ionNavBar class="bar-positive"}}
    {{#ionNavView}}
	  {{>yield}}
  	{{/ionNavView}}
{{/ionBody}}
</template>
```

Any ideas?'

Thanks for the great work!

**Comment by nickw** [comment]
Well that blank space is supposed to be underneath the status bar (clock, battery, etc). I can't remember for sure, but I thought that was just a Cordova setting that was on by default in Meteor.

**Comment by nicholasalanbrown** [comment]
Found the answer here:
https://github.com/meteoric/meteor-ionic/issues/173
This should really be called out somewhere more explicitly...

**Comment by nickw** [comment]
Hmm I've never had to explicitly set that option in any of my apps - it always just worked.

**Comment by nicholasalanbrown** [comment]
Not sure what change in Meteor/another package made this necessary, but this fixed it for me:
```
if (Meteor.isCordova) {
  document.addEventListener("deviceready", function() {
    StatusBar.overlaysWebView(true);
    StatusBar.styleLightContent();
  }, false);
}
```

**Comment by nickw** [comment]
Ah, actually it appears I have these settings in my default [mobile-config.js](https://github.com/meteoric/meteorhunt/blob/master/mobile-config.js#L42-L43)
