### ISSUE TITLE
Ionic Cards on the Roadmap?

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteoric/meteor-ionic#261]
Was looking through the Ionic docs and saw the "Ionic Cards" components and wondered if there were on the roadmap for Meteoric:

http://ionicframework.com/docs/components/#cards

**Comment by nickw** [comment]
None of the components in the `http://ionicframework.com/docs/components/` list require any Meteoric integration - they are just static CSS components and are all already included along with the `https://github.com/meteoric/ionic-sass` package.

**Comment by nicholasalanbrown** [comment]
Ah, that makes sense. Thanks!
