### ISSUE TITLE
Can't open external url

### ISSUE THREAD

**Issue by sweetticket** [meteoric/meteor-ionic#270]
I'm trying to redirect to an external url dynamically using jquery. I've tried the following but none of them work:
```
window.open(my_url, '_blank');
window.open(my_url, '_blank', 'location=yes');
window.open(my_url, '_system');
```
In Xcode I'm getting the error "whitelist rejection." I looked it up and found that i might need to add my_url to an array called ExternalHosts in a cordova plist file, but I'm not sure where this belongs in the meteor-ionic set-up.

**Comment by gwendall** [comment]
See [here](http://docs.meteor.com/#/full/App-setPreference).
