### ISSUE TITLE
Modals don't work if the first child of the template is a comment

### ISSUE THREAD

**Issue by pcavadas** [meteoric/meteor-ionic#271]
Modals don't work properly if the first child of the modal's template is a comment (HTML or Spacebars comment).

Example:

``` handlebars
<template name="_mModal">
    <!-- My comment -->
    {{#ionModal title="My Modal"}}
        <div class="padding">
            Modal Content Goes Here
        </div>
    {{/ionModal}}
</template>
```

This won't work. Same problem with a Spacebars comment: `{{! My comment }}`.

The problem comes from this line in the `IonModal.open` function, in the `ionModal.js` file (line 24):

``` javascript
var $modalBackdrop = $(view.firstNode());
```

`firstNode` function is retrieving the comment node instead of the expected `div.modal-backdrop` node.

Why not simply use this code instead?

``` javascript
var $modalBackdrop = $('.modal-backdrop');
```

BTW, this issue may be present in other components. I didn't check, but a quick search for `firstNode` word through Github shows the following components:
- ionBackdrop
- ionLoading
- ionActionSheet
- ionPopover
- ionPopup
- ionModal

**Comment by descartes1** [comment]
Can confirm this for modal. Modal won't close with comment.
