### ISSUE TITLE
Bug: IonNavigation.skipTransitions causes ionNavBackButton to disappear when switching tabs

### ISSUE THREAD

**Issue by abhishekbatra** [meteoric/meteor-ionic#273]
Hi,

If a `ionNavView` contains `ionTabs` and a `ionNavBackButton`, the back button disappears on switching tabs.

This happens because on switching tabs `IonNavigation.skipTransitions` is set to true: [source link] (https://github.com/meteoric/meteor-ionic/blob/bcd018e4281d625f919b016b816ccac8ce4bd71a/components/ionTab/ionTab.js#L9)

Hence. when `removeElement` is called for the nav bar, the back button gets deleted: [source link] (https://github.com/meteoric/meteor-ionic/blob/ab050a67c55d5507bd0878635c7d90ae48bf4dce/components/ionNavBar/ionNavBar.js#L72)

Thanks

**Comment by abhishekbatra** [comment]
A suggested workaround:

The  above scenario would occur if the following code for including a back button is present only in a layout template:

```
{{#contentFor "headerButtonLeft"}}
		{{>ionNavBackButton}}
	{{/contentFor}}
```

Instead, include this code in all the individual tab templates.

**Comment by nickw** [comment]
I think this is the appropriate behavior. Switching tabs should also set up a new "navigation stack". There shouldn't be anything to "go back" to after switching tabs.
