### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by aunz** [meteoric/meteor-ionic#28]
Instead of having to manually add the meteoric:ionic-sass package
Inside the main meteoric:ionic package.js, add the following:

```javascript
api.addFiles(['ionic/css/ionic.min.css'
        ,'ionic/fonts/ionicons.eot'
        ,'ionic/fonts/ionicons.ttf'
        ,'ionic/fonts/ionicons.svg'
        ,'ionic/fonts/ionicons.woff'
        ],'client',{isAsset:true});

api.addFiles('linkToCss.html','client');
```

Assuming you put the ionic folder inside the package

Then, in linkToCss.html, insert:

link rel="stylesheet" type="text/css" href="/packages/meteoric_ionic/ionic/css/ionic.min.js"

Would this be a better approach?

**Comment by nickw** [comment]
We are currently using the SASS versions of the Ionic framework that can be customized using SASS variables, as opposed to the static/minified CSS versions which would require you to manually overwrite CSS rules. It looks like your suggestion is using static CSS?

**Comment by aunz** [comment]
Yes it's correct, I am using the static CSS. I presume users shouldn't need to toil away the CSS much. If they need to change any rule, they can always override in a new CSS file? cheers

**Comment by nickw** [comment]
The advantage to using the SASS version is that you can customize the output of the SASS using variables rather than overriding / duplicating CSS. e.g. with one line of code `$positive: #2196F3;` you can change the color of dozens of UI elements.
