### ISSUE TITLE
Pass variable to modal

### ISSUE THREAD

**Issue by shactdeveloper** [meteoric/meteor-ionic#281]
Hi, im opening a modal like this:
< a data-ion-modal="AddContact" class="select-user">

I need to pass a variable to my AddContact template.. how can I do this ?

Thanks!

**Comment by gwendall** [comment]
You can pass whatever data your want to the modal through ```[data]``` attributes. For example, this will make the variable ```doc = "x"``` available to the template:

```html
<a data-ion-modal="AddContact" class="select-user" data-doc="x"/>
```
