### ISSUE TITLE
Is Ionic's Floating Labels for Text Input supported in this package?

### ISSUE THREAD

**Issue by rohanray** [meteoric/meteor-ionic#283]
I am trying to use floating labels available @ http://ionicframework.com/docs/components/#forms-floating-labels. However, once I click inside the textbox, the floating labels do not appear. Somehow, the opacity of the span tag with the class input-label does not change its opacity from 0 to 1.

**Comment by jagzatsnapwiz** [comment]
the floating effect does not appear because the 'has-input' class is missing.

**Comment by jagzviruz** [comment]
the has-input class on the parent of the label triggers the effect. Please share a sample of your implementation.

**Comment by rohanray** [comment]
Hi, @jagzviruz I will try to share my code today probably on Meteorpad.

**Comment by rohanray** [comment]
Hi @jagzviruz I have created a Meteorpad @ http://meteorpad.com/pad/bn38rssH3CLdJbAaY/Ionic%20Floating%20Label However, I think Meteorpad still does not support scss and hence, the app is not working as expected. Perhaps, you can download it and run it locally. Please let me know if you need additional details. Thanks a lot in advance!

**Comment by rohanray** [comment]
Hi @nickw, please can you have  a look  into this? Let me know if you need more details.

**Comment by jorjordandan** [comment]
It works fine, but a bit of javascript is needed to add the `has-input` class ... this works:

    $('.item-floating-label>input').on('keyup', function(){
	$(this).val() ? $(this).prev().addClass('has-input') : $(this).prev().removeClass('has-input'); 
    });

**Comment by rohanray** [comment]
@jorjordandan It's working flawless now. Thanks a lot!

**Comment by SaverioCaminiti** [comment]
There is an alternative solution that uses `ng-class` to control the `has-input` class on your `input-label`, like this:

    <label class="item item-input item-floating-label">
      <span class="input-label" ng-class="{'has-input': username}">Choose a username</span>
      <input type="text" placeholder="Choose a username" ng-model="username">
    </label>

**Comment by rohanray** [comment]
@SaverioCaminiti I think meteoric was designed to use Ionic without using Angluar. So not sure if that would be a valid solution for meteoric unless I'm missing something.
