### ISSUE TITLE
Cards, etc?

### ISSUE THREAD

**Issue by arnoldgamboa** [meteoric/meteor-ionic#288]
Hi,

I'm looking at Ionic components here: http://ionicframework.com/docs/components/

It doesn't seem all of the components are supported, like card? Can you confirm?

Thanks!

**Comment by omeid** [comment]
Card is just a css only component, just use it. :)

**Comment by arnoldgamboa** [comment]
So techinically all ionic components can be used here?

Sent from iPhone




On Mon, Aug 24, 2015 at 4:17 AM -0700, "omeid" <notifications@github.com> wrote:












Card is just a css only component, just use it. :)

**Comment by omeid** [comment]
CSS only components can be used as is, those with JavaScript part has been mostly ported from AngularJS to Blaze or microjs libraries.
