### ISSUE TITLE
Scroll Events Not Firing

### ISSUE THREAD

**Issue by bryantpatterson** [meteoric/meteor-ionic#298]
I'm trying to implement a scroll-to-fix feature for item-headers, however, I can't get scroll events to fire. My test code is pretty simple: 

    $(window).scroll(function() {
        console.log("working...");
    }

Am I missing something? I've placed this code within onRendered, in a Lib folder, pretty much everywhere with no luck.

**Comment by nickw** [comment]
In Ionic the `body` doesn't scroll. There's a dedicated div for scrolling content that has the classes `.content.overflow-scroll`. You'll want to monitor the scroll event on that div.

**Comment by bryantpatterson** [comment]
Perfect. Everything is working great. Thanks.

**Comment by xpluscal** [comment]
@bryantpatterson How did you monitor the scrolling content?

**Comment by bryantpatterson** [comment]
@xpluscal This is how I am handling it in a messaging app I have running on iOS. As a hobbyist developer, I can't guarantee this is the proper way to do this, but it works. The first line scrolls to the bottom upon render, and everything from `this.find` on handles scrolling on each additional message, similar to the Messages app on iOS.

The `uihooks` portion came from Discover Meteor's Animations chapter (https://book.discovermeteor.com/chapter/animations) which is behind the paywall unfortunately.

```javascript
Template.messagesIndex.onRendered(function () {
  // Auto scroll logic
  $('.content.overflow-scroll').scrollTop($('.content.overflow-scroll')[0].scrollHeight);
  this.find('#messages-list')._uihooks = {
    insertElement: function (node, next) {
     $(node).insertBefore(next);
     var scrollDiv = $('.content.overflow-scroll')[0];
     $('.content.overflow-scroll').scrollTop($('.content.overflow-scroll')[0].scrollHeight);
    }
  };
});
```
