### ISSUE TITLE
How to make item-toggle in form demo?

### ISSUE THREAD

**Issue by MichaelJCole** [meteoric/meteor-ionic#302]
Hopefully this is an easy one.

The form demo has a toggle on the "Forms" page:

http://meteor-ionic.meteor.com/forms

Which looks like it comes from here:  https://github.com/meteoric/demo/blob/master/client/templates/forms/forms.html#L12

How would you make that control w/o quickforms?

**Comment by nickw** [comment]
It doesn't require any JavaScript, just HTML and CSS:
http://ionicframework.com/docs/components/#toggle

**Comment by MichaelJCole** [comment]
Nice!  Thanks Nick!
