### ISSUE TITLE
android keyboard not pushing view up on input focus

### ISSUE THREAD

**Issue by sasikanth513** [meteoric/meteor-ionic#307]
I'm using latest version of the pcakage and I saw #89 issue and I commented out

```
Cordova.depends({
   'com.ionic.keyboard': '1.0.4'
 });
```

 in package.js file and it is working fine in `iOS` but not scrolling to input when input is focused in android but pushing view to keyboard height.

I'm not wrapping my code in `ionView` and `ionContent` also.

Is this issue related to here if I'm not following above things.

Any solution for this?

**Comment by rohanray** [comment]
+1

**Comment by rahul-sdei** [comment]
did you find any solution for this?

**Comment by Roshdy** [comment]
+1

**Comment by da314pc** [comment]
if your still using it:
these methods were removed from cordova android:
"native.keyboardshow" & "native.keyboardhide",

so these lines of code won't get triggered:
https://github.com/meteoric/meteor-ionic/blob/93a2d4e48342b7c8ea5670ef76adc9056e133a0f/components/ionKeyboard/ionKeyboard.js#L45-L92

Try removing this from your config.xml
 <feature name="Keyboard">
        <param name="android-package" onload="true" value="org.apache.cordova.labs.keyboard.Keyboard" />
</feature>

Also update your ionic keyboard to: ionic-plugin-keyboard@2.2.1

**Comment by da314pc** [comment]
remove the cordova plugin keyboard from your config.xml
