### ISSUE TITLE
headerTitle and template data

### ISSUE THREAD

**Issue by geritol** [meteoric/meteor-ionic#31]
Template data (set w ironRouter) shows up in content but does not appear in header.

    {{#contentFor "headerTitle"}}
        <h1 class="title">{{_id}}</h1> 
    {{/contentFor}}
    {{#ionView}}
        {{#ionContent}}
            <h1>{{_id}}</h1> 
        {{/ionContent}}
    {{/ionView}}

**Comment by nickw** [comment]
Do you have an `ionHeaderBar` or `ionNavBar` in your layout?

**Comment by geritol** [comment]
ionNavBar in the layout.

**Comment by fpoirier1** [comment]
This worked for me.

    {{#contentFor region="headerTitle" data=this}}
        <h1 class="title">{{_id}}</h1> 
    {{/contentFor}}
    
     {{#ionView}}
        {{#ionContent}}
           <h1>{{_id}}</h1> 
        {{/ionContent}}
    {{/ionView}}
