### ISSUE TITLE
Passing data to ionModal?

### ISSUE THREAD

**Issue by daniel** [meteoric/meteor-ionic#314]
Is it possible to pass the data from the template that opens the ionModal?
For example if I have a template that shows a blog post and in that template I have a button to open a "edit post" template as a modal. Then I want the be able to access the post data from the "edit post" template and it's helpers.

**Comment by xpluscal** [comment]
Hey @daniel,
are you using iron-router to get to the blog post?
In this case you probably have the _id as a parameter available. It is accessible in your modals-template via:

```javascript
Template.yourTemplate.helpers({
	collection: function () {
		return Collection.findOne({_id: Router.current().params._id});	
	},
})
```

Hope this helps

**Comment by daniel** [comment]
Thanks! I'll try that.

**Comment by abhishekbatra** [comment]
Closed, but still adding something that I use:

```javascript
'click .selector': function(event, instance) {
		var templateName = "modalTemplate";
		var currentData = {'ion-modal': "modalTemplate"};
		_.extend(currentData, Template.currentData());
		
		IonModal.open(templateName, currentData);
	}
```
