### ISSUE TITLE
Images no longer showing

### ISSUE THREAD

**Issue by elie222** [meteoric/meteor-ionic#324]
I've got no idea why, but images in my ionic app have stopped showing. If I go to the browser, I see the html is correct and if I go to the url of the app, the image loads up.

What's really strange is that it just suddenly stopped working. I went back a few commits on git and the images still don't load even though I'm positive that they did in the past. Any ideas why this could be happening or how to fix it?

**Comment by pors** [comment]
I don't know how you load the images but maybe this is the cause?
https://github.com/meteor/meteor/issues/4560

**Comment by elie222** [comment]
I'm running the app in a browser

**Comment by elie222** [comment]
My code looks something like this:
```
   <div class="item item-avatar">
        <img src="/some-image.png">
        <h2>John Smith</h2>
        <p>Some text</p>
    </div>
```

Going to the image url in the browser loads the correct image.

**Comment by elie222** [comment]
No idea what happened. Images are now showing. After restarting my computer things are magically working again.
