### ISSUE TITLE
tabs stay on the top instead bottom on android device

### ISSUE THREAD

**Issue by GYF1** [meteoric/meteor-ionic#33]
I find it can be set use angular service $ionicConfigProvider as below code:

```
$ionicConfigProvider.tabs.position("bottom"); //Places them at the bottom for all OS
$ionicConfigProvider.tabs.style("standard"); //Makes them all look the same across all OS
```
how to deal with it in meteor-ionic ?
Thanks for your help

![qq20150120-2 2x](https://cloud.githubusercontent.com/assets/6308804/5811013/9b3aab90-a08a-11e4-8471-b3f7506f1c78.png)

**Comment by nickw** [comment]
Ah that's not currently possible. Personally I prefer to allow the platform to determine the tab location (Android on top, iOS on bottom), but I'm open to a PR that allows more flexibility.
