### ISSUE TITLE
Keyboard doesn't open properly

### ISSUE THREAD

**Issue by timothyarmes** [meteoric/meteor-ionic#330]
Hi,

I have a problem that's been driving me mad for over a month: the keyboard is too low on the iOS simulator:

<img width="459" alt="screen shot 2015-10-07 at 14 55 32" src="https://cloud.githubusercontent.com/assets/1092550/10337953/819732c6-6d03-11e5-9a19-4a9f1f0ac1ed.PNG">

You can see the top of the keyboard at the bottom of the screen

I can't trace it down to a source, so I don't know if the problem's coming from Meteoric, Ionic or Cordova.
I haven't seen the issue on my iPhone, but I've never seen any discrepancy between the simulator and the hardware before so I'm concerned that although I don't see the issue, other users might.

Has anyone else seen this happen?

Regards,

Tim

**Comment by cosio55** [comment]
Have you tried pressing ⌘K to toggle the keyboard on the simulator?

**Comment by timothyarmes** [comment]
Hmm, it seems that disconnecting the hardware keyboard 'solves' the issue. 

Thx.
