### ISSUE TITLE
ionTab unable to retrieve badge count variable from helper

### ISSUE THREAD

**Issue by LucNaterop** [meteoric/meteor-ionic#336]
This was asked before [here](https://github.com/meteoric/meteor-ionic/issues/188) and [here](https://github.com/meteoric/meteor-ionic/issues/48), yet it was never solved. Let me state the problem again:

```javascript
{{#ionTabs style="ios" class="has-badge"}}
    {{> ionTab title="Notifications" path="notifications" badgeNumber="{{badgeCount}}" iconOn="ios-bell" iconOff="ios-bell-outline" class="tab-item-positive notificationstab" }}
{{/ionTabs}}
```

gives me 

![Alt Text](http://i.imgur.com/TIV33gT.jpg)

Therefore, I cannot access the helper variable {{badgeCount}}  there. And yes, the helper does exist.

**Comment by fishdude** [comment]
+1 on this.

**Comment by daveeel** [comment]
You have to make 'badgeCount' a template helper function name which returns the number.
Attribute value like {{badgeCount}} won't expanded

**Comment by LucNaterop** [comment]
Oh...my bad. It works now, thanks!

**Comment by chansdad** [comment]
This still is an issue .. I am just not able to get this to work ..
<img width="116" alt="screen shot 2018-01-26 at 3 14 37 am" src="https://user-images.githubusercontent.com/3308018/35430674-524e8088-0247-11e8-9c9b-45f93b6900f2.png">

I have the main template tabs and in that 

```
<template name="tabs">
    {{#ionTabs style="ios" class="has-badge"}}
{{> ionTab title="alerts" path="useralerts" badgeNumber="{{useralertcount}}" iconOff="android-notifications-off" iconOn="android-notifications" class="tab-item-positive"}}
          
    {{/ionTabs}}
</template>
```

and  i made the helper function useralertcount  as 

```
Template.tabs.helpers({
 'useralertcount': function () {
        return Useralerts.find({}).count();
    }
});

```

why is it that i am seeing the curly's and not hte actual badge count? Appreciate the help.
