### ISSUE TITLE
On button click active effects

### ISSUE THREAD

**Issue by rclai** [meteoric/meteor-ionic#34]
I noticed that there were no ```:active``` CSS rules on buttons, then I realized that the Ionic active effects are done via JavaScript by injecting the ```activated``` class and removing it.

http://ionicframework.com/docs/components/#buttons

Are you guys able to put a global listener somewhere for the buttons (ionBody perhaps?):

```
$(document).on('mousedown', '.button', function () {
    $(this).addClass('activated');
}).on('mouseup', '.button', function () {
    $(this).removeClass('activated');
});
```

**Comment by nickw** [comment]
Ah interesting. We could create an `ionButton` component pretty easily. Or, I've been putting all global event handlers on the `ionBody` element, so we could add your listener there. Are there any downsides you can think of to either approach?

**Comment by rclai** [comment]
Performance-wise, putting the event handler on ```ionBody``` is better since we get to leverage the efficiency of event delegation.

Also, I found out that the ```.activated``` class is an alias to the ```.active``` class. There's like 140 occurrences of it on the Ionic style sheet. What a waste of file size, what were they thinking?

**Comment by nickw** [comment]
Works for, feel free to create a PR for this. I may not get to it until this weekend.

**Comment by nickw** [comment]
Ah I see you added it with the multi-modal PR. Looking at that now…

**Comment by rclai** [comment]
I should've created a fork so I could've submitted it separately.

**Comment by nickw** [comment]
Closed in https://github.com/meteoric/meteor-ionic/pull/38

**Comment by rclai** [comment]
Sweet, thanks.
