### ISSUE TITLE
Migrating to Ionic 2

### ISSUE THREAD

**Issue by Garethderioth** [meteoric/meteor-ionic#340]
Hello, 

I just see that Ionic 2 is on the way and looks amazing (Material Design, Full iOS design) I want to know If there is a way to make a quick migrate to Meteor Ionic, or what step could I try?

http://ionicframework.com/docs/v2/getting-started/migration/

Regards.

**Comment by nickw** [comment]
I don't think it would be a trivial migration, and I personally don't have plans tackling it now that Meteor has good support for Angular.

**Comment by pors** [comment]
Hi @nickw, does that mean that there is no maintainer for this package anymore? My guess is that most Meteor users don't want to go the Angular way (Blaze and React seem the most popular).

**Comment by nickw** [comment]
I'm not officially abandoning this project (yet), but I'm not using it personally, and wouldn't recommend it for anything more "serious" than a prototype or MVP. For users that don't want to use Angular, there are React alternatives such as http://reapp.io/.

**Comment by pors** [comment]
OK, that's good to know. We are using meteoric for an MVP now, but will have to plan for something else later on then.
What are you using personally for mobile (cordova powered) apps based on Meteor? Is there anything for Blaze that you know?

**Comment by cosio55** [comment]
Yes, I made everything, the problem I’m having is with that specific Cordova plugin, that’s what I need help with.

**Comment by nickw** [comment]
@pors No, I haven't seen anything else for Blaze. Personally I haven't found Blaze to scale well with an app's complexity, and it doesn't seem to be a priority for MDG, so I think React or Angular are the way to go moving forward.

**Comment by pors** [comment]
@nickw cool thanks, time to learn React :)

**Comment by xpluscal** [comment]
@nickw Do you see any alternatives to React as a cross-platform-ui-framework?
Angular might be a choice now but I don't see any Integration for Ionic V2 coming up.

**Comment by meteorjs3000** [comment]
OMG, I built entire apps using `meteor-ionic`, but now I need to use an ionic package that will continue to be maintained.

I know neither Angular nor React, which one should I learn if I want to continue using an actively-maintained Ionic package? Is there another UI similar to Ionic that will be better supported by Meteor's ecosystems?

**Comment by xpluscal** [comment]
Same here

meteorjs3000 <notifications@github.com> schrieb am Do., 26. Nov. 2015 22:37:

**Comment by pors** [comment]
I have the same situation, and I played a bit around with reapp. My conclusion is that it is still far from ready for production. It would be cool if there would be a react-ionic library, but what I found so far is very basic.

What we are doing now is porting our app slowly to react, but keeping ionic. So step by step we port one of the components in meteor-ionic to a react version of it. All the stuff we don't need we won't implement (yet).
It's not that difficult and the meteor-ionic package is a great starting point for implementing a react-ionic version of it.

**Comment by vertangelx** [comment]
I decided to start learning Angular as the Ionic framework appears to be the best for developing cross-platform apps. 

Even though React seems so cool. And Angular2's arrival will cause some rewriting of code. Will love to have more people's opinions on how we should proceed from here.

**Comment by Garethderioth** [comment]
I just check this library and looks like a good alternative to use a cross-framework for mobile. https://github.com/nobutakaoshiro/meteor-framework7-ios-material

**Comment by jetstreamin** [comment]
I was looking at Reapp but its in Alpha and also Aurelia.io

**Comment by malixsys** [comment]
Don't worry: https://atmospherejs.com/barbatus/ionic2-meteor

**Comment by xpluscal** [comment]
@malixsys : Do you know more about this? This is still tied to angular isn't it?

**Comment by malixsys** [comment]
Depends what you mean by "tied" but yes...
http://blog.ionic.io/angular-2-ionic
Is this a bad thing??

**Comment by xpluscal** [comment]
Well, I guess this is more of a personal choice.
I prefer working with Blaze since it feels a lot more natural to work with in Meteor to me. 

That’s what made this package so promising.

**Comment by pors** [comment]
For anyone who is interested (and prefers React over Blaze), I created a port of Meteoric for React, see https://github.com/pors/reactionic/. It should be quite easy to port your apps as I tried to keep it as much as possible in line with Meteoric. Let me know if I can help!

Demo is here: http://pors.github.io/reactionic/#demo
