### ISSUE TITLE
Template instance custom properties inaccessible inside ion tags

### ISSUE THREAD

**Issue by rclai** [meteoric/meteor-ionic#35]
When you have something like this:

```
<template name="template">
   {{#ionBody}}
      {{#ionSomething}}
            {{myCustomHelper}}
      {{/ionSomething}}
   {{/ionBody}}
</template>
```

And you try to do this pattern:

```
Template.template.created = function () {
    this.myCustomProperty = new ReactiveVar();
};

Template.template.helpers({
    myCustomHelper: function () {
        return Template.instance().myCustomProperty.get();
    }
});
```

You won't be able to access that custom property that you've defined in the ```created``` callback because the template scope has changed. I was wondering whether you guys have ran into this issue and what you guys have done to deal with it?

This pattern is similar to what's being demonstrated here: https://www.discovermeteor.com/blog/template-level-subscriptions/

What I have done was set custom properties in the ```this.data``` property, but according to Meteor docs, that's supposed to be read-only.

**Comment by nickw** [comment]
Hmm that's a bummer. The only thing I can think of would be to make `myCustomHelper` into its own template and move `myCustomProperty` there. Hopefully someone with more knowledge can chime in with a more Meteor-like approach.

**Comment by rclai** [comment]
Turns out this is a meteor bug: https://github.com/meteor/meteor/issues/3540

You're off the hook hehe.
