### ISSUE TITLE
Meteoric vs Ionic implementation on Meteor

### ISSUE THREAD

**Issue by arnoldgamboa** [meteoric/meteor-ionic#353]
I saw that Meteor 1.2 now has Angular support, and thus Ionic Framework can now run 'naturally' within meteor. I've been looking at the Ionic "WhatsApp" Meteor tutorial and it sure looks heavily Angular, obviously. 

I used Angular for sometime before moving to Meteor. And honestly, it's Ionic that keeps me from completely leaving Angular. Until Meteoric.

May I know your thoughts about investing time with Meteoric vs. just using Ionic (and Angular) within Meteor?

**Comment by nickw** [comment]
Meteoric is great for rapid prototyping and simple apps, but I'm no longer maintaining this package and am recommending official Angular Ionic for serious, production apps.
