### ISSUE TITLE
alignTitle on ionNavBar not working

### ISSUE THREAD

**Issue by Loschcode** [meteoric/meteor-ionic#359]
I'm trying to do something like `{{> ionNavBar alignTitle="left"}}` to force the title to be on the left but it doesn't seem to work. The only way I got it working was to do it manually without `meteor-ionic`

    
    {{#contentFor "headerTitle"}}

      <h1 class="title title-center">My Awesome Title</h1>

    {{/contentFor}}

It works, but it's not using the system which break all flexibility. Did I do something wrong or isn't it working for real ?

**Comment by cedla** [comment]
The problem is the same as #292. A pull request has been submitted, but it still hasn't been merge yet.

For now, there a 2 little tricks you can do:

- you can add the `title-left` CSS class to your title:
```js
<h1 class="title title-left">My Awesome Title</h1>
```

- or you can do it in Javascript, with this hack:
```js
Template.ionNavBar.onCreated(function () {
    this.alignTitle = 'left';
});
```

**Comment by Loschcode** [comment]
Well it's not working on Android whatsoever, took me the night to figure that out, ok for the duplicate issue
