### ISSUE TITLE
ionItem routes not working after update meteoric:ionic@0.1.10

### ISSUE THREAD

**Issue by dancering** [meteoric/meteor-ionic#36]
After update my code doesn't work anymore with routes in <#ionItem>, options path='' and route='' crashes at debug with 'call error of undefined'. The only option working now is href='/xxxxxx'

**Comment by nickw** [comment]
@benstr @spencercarli can you guys take a quick look and see if this was one of your PRs?

**Comment by benstr** [comment]
@nickw my last PR did not get pushed to atmosphere yet I believe.

**Comment by nickw** [comment]
@dancering I just published 0.1.11, let me know if you are still experiencing this after updating.

**Comment by benstr** [comment]
Sorry about that guys, I usually add Lo-Dash without thinking. This time it bit me because underscore is not as magical. I will make sure not to make the mistake again on this framework :)

**Comment by dancering** [comment]
All is working again. Thanks!
