### ISSUE TITLE
Ionic 1.2 discussion

### ISSUE THREAD

**Issue by logankoester** [meteoric/meteor-ionic#365]
Ionic 1.2 was [announced this week](http://blog.ionic.io/announcing-ionic-1-2/). Anyone looking into it yet?

**Comment by aesmon** [comment]
I believe this package is no longer maintained. Seems that people are migrating towards React, not sure what the next big thing will be, I found reapp to be a bit buggy.

Atm I'm just extending Meteoric Ionic features on my local project

**Comment by benstr** [comment]
@aesmon is correct. Closing this issue.
