### ISSUE TITLE
How to upgrade meteor-ionic with Meteor 1.3 ?

### ISSUE THREAD

**Issue by danlg** [meteoric/meteor-ionic#380]
@nickw Basically, the issue is that `meteor-ionic` depends on `ionic-plugin-keyboard` which is not suggested to be a good addition which WKWebView (the default now with Meteor 1.3)

As suggested by @chaffeqa https://github.com/driftyco/ionic-plugin-keyboard/issues/98

> I actually would suggest ditching the ionic keyboard plugin for iOS when using the WKWebView.
> I also suggest defaulting to native scrolling so that iOS has full control over the functioning of the keyboard + scrolling logic.  I have tested this and the native functionality works great.

I've tried to do it but it was not successful (for details see my comments on this issuehttps://github.com/driftyco/ionic-plugin-keyboard/issues/98) . 

@nickw Do you have any idea on how to do ? I am in the middle of a production project now and I don't have the resources to migrate to another framework just yet. Thanks for your advice.

**Comment by nickw** [comment]
@danlg you can probably just fork the project and remove these lines: https://github.com/meteoric/meteor-ionic/blob/master/package.js#L8-L10

Then install the package from your fork.
