### ISSUE TITLE
Page transition when using sideMenu

### ISSUE THREAD

**Issue by Batmunkh** [meteoric/meteor-ionic#39]
First of all thank you all for this great package. My issue is when I'm using the sideMenu as navigation there's still a slide in animation during page transition. This creates double slide effects with the sideNavigation closing and the page transitioning with slide animation. Is there a way to disable the slide effect when using the sideMenu as navigation?

**Comment by nickw** [comment]
Ah good question, haven't had that usecase myself yet.

We are currently skipping transitions when using tab navigation, we just set `IonNavigation.skipTransitions = true;` in a click handler:

https://github.com/meteoric/meteor-ionic/blob/master/components/ionTab/ionTab.js#L25

I think you could do the same in your sidemenu.

**Comment by Batmunkh** [comment]
Awesome let me try it out.

**Comment by Batmunkh** [comment]
Great this worked like a charm. Appreciate the fast response.

**Comment by MrMegamind** [comment]
where do i find this file ? i am using ubuntu
if i change the local project .meteor folder then it doesnt as the file gets overwriten on each compile. please suggest path

**Comment by thomers** [comment]
Same question - where to include this, to avoid the slide-in animation?

**Comment by thomers** [comment]
Note - I put it into the menu list items 

  <a class="item item-icon-left" href="{{pathFor route='home'}}" onClick="IonNavigation.skipTransitions = true; return true;" data-ion-menu-close>
                            {{> ionIcon icon="chatboxes" class="assertive"}}
                            Home
                        </a>

But this seems a bit redundant - maybe this should be put into a ionSideMenu option?)

**Comment by insaneinc01** [comment]
Anyone knows how to globally disable all IonNavigation transitions?
