### ISSUE TITLE
Segment Control

### ISSUE THREAD

**Issue by vertangelx** [meteoric/meteor-ionic#41]
Is it possible to create segmented control (UISegmentedControl) using `meteor-ionic`?

Theres `https://github.com/tinga-dev/ti-ionic-segmented-control` but it can't be used directly in `meteor-ionic`.

**Comment by nickw** [comment]
Yeah, that's actually a really good example of a simple component that can easily be re-created in meteor - so I went ahead and did it :) Let me know if this works out for you: http://cl.ly/0W2P0A3l3o2U. I think the code is actually a lot cleaner and more flexible than the Angular code, too.
