### ISSUE TITLE
Blending tabs with header

### ISSUE THREAD

**Issue by meteorjs3000** [meteoric/meteor-ionic#42]
Where do we place the code for the top-positioned tabs if we want to create (something like this)[http://ionicframework.com/docs/components/#striped-style-tabs]?

Currently my template looks like the following

	<template name="contentTemplate">

		{{#contentFor "headerTitle"}}
			<h1 class="title">Title</h1>
		{{/contentFor}}

		{{#ionView}}

			<div class="tabs-striped tabs-top tabs-background-positive tabs-color-light">
				<div class="tabs">
					<a class="tab-item active" href="#">
						First
					</a>
					<a class="tab-item" href="#">
						Second
					</a>
				</div>
			</div>

		{{#ionContent}}
			<div class="list">
				{{#each items}}
					{{ name }}
				{{/each}}
			</div>
		{{/ionContent}}
		{{/ionView}}

	</template>

but the top tabs are blocking the content

![image](https://cloud.githubusercontent.com/assets/8838841/5890087/7162f5da-a417-11e4-9bac-7328d008025f.png)

**Comment by nickw** [comment]
The way ionic works is that the `ion-content` component has to know about which components are above or below it. If you use the built-in `ionTabs`, `ionHeaderBar`, `ionFooterBar`, etc components, the `ionContent` component will automatically have the necessary `has-tabs`, `has-header`, etc classes.

So in your case, you can either use the `ionTabs` component, or just add the necessary class to your `ionContent` like so:

```
{{#ionContent class="has-tabs-top"}}
```
