### ISSUE TITLE
how would one go about contributing the popup and slidebox components?

### ISSUE THREAD

**Issue by faceyspacey** [meteoric/meteor-ionic#43]
Anything I should know before hand?

**Comment by nickw** [comment]
Nope not really. I just try to mimic the Ionic APIs as close as possible and ideally not add any custom CSS. You can look at the way I implemented `ionActionSheet` to see how `ionPopup` might be implemented. For the slidebox I was probably just going to look for a good 3rd party plugin to include the way I did for the side menu stuff.

**Comment by dcsan** [comment]
FWIW slick.js doesn't seem to work within a meteoric app. I'm still looking into what other options there maybe - has anyone else got a carousel working with this?

it maybe that whatever events ionic is preventDefaulg-ing will stop any carousel from working, and not sure where to look to prevent these being prevented.

**Comment by nickw** [comment]
@dcsan have you seen #5? Or is this statement in reaction to #5?

**Comment by maersu** [comment]
@dcsan I have a working carousel with http://www.owlcarousel.owlgraphic.com/

Is your problem, that the carousel doesn't work with dragging/touch? Snapper.js captures all "touchToDrag" events

You can disable this with
```
Template.appLayout.rendered = function () {
    IonSideMenu.snapper.settings({touchToDrag: false});
};
```

**Comment by nickw** [comment]
@dcsan sorry I was confusing `snap.js` with `slick.js` :)

To get around `snap.js` dragging, you can also add a `data-snap-ignore` attribute to any element or container.
