### ISSUE TITLE
using ionSideMenus

### ISSUE THREAD

**Issue by dcsan** [meteoric/meteor-ionic#46]
i see you have something ported for side menus, but could you explain how to replace the required angular directive? Or is that already done?

http://ionicframework.com/docs/api/directive/ionSideMenus/

```
function ContentController($scope, $ionicSideMenuDelegate) {
  $scope.toggleLeft = function() {
    $ionicSideMenuDelegate.toggleLeft();
  };
}
```

looks like something needs to be connected to get the scrolling across to work?

is there an example anywhere of these being used? i couldn't see it in the two example apps.

**Comment by dcsan** [comment]
just to recap what i tried:

taking the ionic markup example:
```xml

<ion-side-menus>
  <!-- Center content -->
  <ion-side-menu-content ng-controller="ContentController">
  </ion-side-menu-content>

  <!-- Left menu -->
  <ion-side-menu side="left">
  </ion-side-menu>

  <!-- Right menu -->
  <ion-side-menu side="right">
  </ion-side-menu>
</ion-side-menus>
```

and converting to your Template tags like:

```
<template name="layout">
  {{#ionBody}}

    {{#ionSideMenus}}

      {{#ionSideMenuContent}}
        side content
      {{#ionSideMenuContent}}

      {{#ionSideMenu side='left'}}
      left
      {{/ionSideMenu }}

      {{#ionSideMenu side='right'}}
      right
      {{/ionSideMenu }}


    {{/ionSideMenus}}

  {{/ionBody}}
</template>
```

note this is in the apps main layout (no yield yet for content area)

I left the JS alone hoping that maybe [this](https://github.com/meteoric/meteor-ionic/blob/master/components/ionSideMenu/ionSideMenu.js) would help that.

however what i see is this:

![image](https://cloud.githubusercontent.com/assets/514002/5898894/0fb996de-a509-11e4-90da-f5fe4fa6ba56.png)

unless sideMenus are still work in progress?

**Comment by digilord** [comment]
@dcsan https://github.com/meteoric/demo/blob/master/client/layout.html shows a great example of using the sideMenus code.

**Comment by nickw** [comment]
@dcsan yeah the demo app has an example, I think you're just missing `ionSideMenuContainer`.
