### ISSUE TITLE
Routes without data cause rendering to fail

### ISSUE THREAD

**Issue by digilord** [meteoric/meteor-ionic#47]
When using a route without a data attribute the route fails with:
![image](https://cloud.githubusercontent.com/assets/226351/5900351/466bd4c8-a525-11e4-8777-0c1c1e0d3089.png)

Here is an example of working and non-working code:

```coffeescript
Router.map ->
  @route 'home',
    path: '/'
    action: ->
      # Wait on collections
      # @wait Meteor.subscribe('someCollection')
      @render 'home'

    # If I comment out the below three lines the application fails to load 
    # with the above error in the console.
    # data: ->
    #   # Return some collections pointer
    #   return []

  @route 'login',
    path: '/login'
    action: ->
      @render 'login'
    data: ->
      return []
```

**Comment by nickw** [comment]
#31 and #27 seem to be related to this, but I'm totally stumped on what's causing it and am unable to reproduce.

**Comment by dennisharrison** [comment]
This is still happening w/ 0.1.12

**Comment by nickw** [comment]
Yeah I haven't published a new version yet, will do ASAP.
