### ISSUE TITLE
can't get #ionTabs "has-badge" to work

### ISSUE THREAD

**Issue by hettema** [meteoric/meteor-ionic#48]
With the risk of asking something silly easy, I've been googling around and been unable to get this to work. 

Any idea why the code below refuses to display the badge count? 

```
{{#ionTabs style="ios has-badge"}}
        {{> ionTab title="Home" path="home" iconOff="ios-heart-outline" iconOn="ios-heart" badge="{{badgeCountHelper}}" badge-style="badge-assertive"}}
{{/ionTabs}}
```

**Comment by nickw** [comment]
There's a few things going on here:

1. `has-badge` is a CSS class, not a `style` option:
`{{#ionTabs style="ios has-badge"}}` should be `{{#ionTabs style="ios" class="has-badge"}}`

2. I think `badge="{{badgeCountHelper}}"` should be `badgeNumber="{{badgeCountHelper}}"`

3. `badge-style="badge-assertive"` hasn't been implemented yet, but probably needs to be.

**Comment by hettema** [comment]
Thanks @nickw, I haven't gotten this to work yet but I'll report back with any progress I make.
