### ISSUE TITLE
Slide Box

### ISSUE THREAD

**Issue by nickw** [meteoric/meteor-ionic#5]
http://ionicframework.com/docs/api/directive/ionSlideBox/

**Comment by mikeconstable** [comment]
+1. I'm short on skills to contribute, would be keen to test this component.

**Comment by nickw** [comment]
Potential 3rd party component to utilize: http://owlgraphic.com/owlcarousel/

**Comment by mikeconstable** [comment]
Thanks - looks promising. I'll take a look when I get back to that part of my app.

**Comment by nickw** [comment]
Ended up using https://github.com/kenwheeler/slick/

**Comment by richpowell** [comment]
is the api the same as ionics? Im having trouble implementing this

**Comment by nickw** [comment]
Yeah it's as close as I think I can get it in Meteor. The basic API is:
```
{{#ionSlideBox}}
  {{#ionSlide}}Slide 1{{/ionSlide}}
  {{#ionSlide}}Slide 2{{/ionSlide}}
  {{#ionSlide}}Slide 3{{/ionSlide}}
{{/ionSlideBox}}
```

The available options you can pass to `ionSlideBox` are:
- doesContinue
- autoPlay
- slideInterval
- showPager

There's also an `onSlideChanged` event that you can listen to in your parent template:

```
Template.tutorial.events({
  'onSlideChanged': function(event, template) {
    pageSession.set('currentIndex', event.index);
  }
});
```

**Comment by richpowell** [comment]
Thank you, It works on the phone, but not in the ios simulator.

**Comment by bwhitty** [comment]
I tested it out last night, looks good at least on the web so far.

**Comment by elGusto** [comment]
Why let only a few options of slick to be overriden ?

It would be nice to have access to it's full api.

**Comment by omeid** [comment]
Compatibility with upstream ionic. I think.

**Comment by Jooshuys** [comment]
@nickw you mentioned that in Meteor when using the Slick package, 'onSlideChanged' can be used to capture a slide changed event of a carousel. I'm using the same package and the following code doesn't trigger at all:
```
Template.Examples.events({
	'onSlideChanged': function (event, template) {
		console.log("changed");
	}
});
```
I'm starting my carousel with this code:
```
$('#carousel').slick({
	autoplay: true,
	fade: true,
	autoplaySpeed: 6000,
	speed: 2000
});
```
Any idea what I'm doing wrong?
