### ISSUE TITLE
drag-content="false"

### ISSUE THREAD

**Issue by chrishill627** [meteoric/meteor-ionic#50]
Hi.

Is it possible to use this with your {{#ionSideMenuContent}} ?

Or a suggested work around would be great!

Thanks in advance, awesome package, thanks!

Kind regards

Chrs

**Comment by nickw** [comment]
Hi Chris,

Can you give me some background on this? Is `drag-content` something from Ionic? What is the expected behavior?

Thanks,
Nick

**Comment by danielemeschiari** [comment]
Hi,
it's an `<ion-side-menu-content>` attribute
http://ionicframework.com/docs/api/directive/ionSideMenuContent/

**Comment by chrishill627** [comment]
Yes, I tried to use it like this {{#ionSideMenu drag-content="false"}}

**Comment by nickw** [comment]
Ok guys, you can now pass a `dragContent` option to `ionSideMenuContainer` like so:

```
{{#ionSideMenuContainer dragContent=false}}
```

**Comment by chrishill627** [comment]
Awesome Nick! Much appreciated, great package!

**Comment by chrishill627** [comment]
If you remember give us a shout when you release the version to atmosphere with the fix, I'll keep trying, thanks!
