### ISSUE TITLE
Badge position is not proper

### ISSUE THREAD

**Issue by eeandrew** [meteoric/meteor-ionic#51]
I try to add badge to meteorhunt, here is my code:
```
{{> ionTab title="Trending" path="trending" badgeNumber="10" iconOff="ios-bolt-outline" iconOn="ios-bolt" class="tab-item-positive"}}

        {{> ionTab title="Recent" path="recent" badgeNumber="15" iconOff="ios-clock-outline" iconOn="ios-clock" class="tab-item-positive"}}
```
But the final effect is weird:
![badge-bug](https://cloud.githubusercontent.com/assets/7982269/5916672/9b155d6c-a64e-11e4-89cc-26954c0e4779.gif)

**Comment by nickw** [comment]
Yeah I noticed that too in one of my projects, I had to add this CSS:

```
.tab-item {
  // Ionic bug, needed to position badges:
  position: relative;
}
```

However I just looked and Ionic has this CSS rule:

```
.tab-item.has-badge {
  position: relative;
}
```

So I think we should automatically add the `has-badge` class in `meteor-ionic` if you pass a `badgeCount` option.

**Comment by eeandrew** [comment]
How to sync badgeNumber? It seems badgeNumber is hard coded
