### ISSUE TITLE
Toggle Element

### ISSUE THREAD

**Issue by digilord** [meteoric/meteor-ionic#53]
I have the toggle element in my project. It's not saving state. After looking a little harder I see that you implemented the toggle as an autoforms element instead of a plain form element. Is there any way the people that don't use autoforms could get a version of that ionic element as a plain working form element?

Thanks!

**Comment by nickw** [comment]
You would probably do it the way you would a normal checkbox, just use a template helper to save the state and toggle the `checked` attribute.
