### ISSUE TITLE
Error with path attribute in IonItem

### ISSUE THREAD

**Issue by LeCoupa** [meteoric/meteor-ionic#54]
Hello,

Just found that specifying a `path` attribute for the `ionItem` component triggers the following error client-side:

```javascript
Exception in template helper: TypeError: Cannot read property 'call' of undefined
```

Here is my code:

```handlebars
{{#ionItem path="iTrackStores" buttonRight=true class="item-icon-right"}}
  iTrack {{>ionIcon icon="ios-arrow-forward" class="assertive"}}
{{/ionItem}}
```

And the route definition:

```coffeescript
Router.route 'iTrackStores',
  path: '/itrack/stores'
```

[I've followed this example though](https://github.com/meteoric/demo/blob/master/client/templates/index/index.html).

**Comment by nickw** [comment]
Yeah, that _should_ work. 

@benstr any thoughts on this?

**Comment by benstr** [comment]
Yeah that *should*. I will look into this. In the meantime try calling `route=`, you do not need path since you are not including additional route params.

```
{{#ionItem route="iTrackStores" buttonRight=true class="item-icon-right"}}
  iTrack {{>ionIcon icon="ios-arrow-forward" class="assertive"}}
{{/ionItem}}
```

more info under [Guide.md](https://github.com/meteoric/meteor-ionic/blob/master/GUIDE.md#ionitem)

**Comment by LeCoupa** [comment]
Yes, I also tried `url` but I still have the same error. What I did for the moment is to use a simple `href` but that's not dynamic. :/

```handlebars
{{#ionItem href="/itrack/stores" buttonRight=true class="item-icon-right"}}
  iTrack {{>ionIcon icon="ios-arrow-forward" class="assertive"}}
{{/ionItem}}
```

**Comment by benstr** [comment]
It works fine for me. Can you verify the package version is `version: "0.1.12"`?

We were having this issue in `version: "0.1.10"` and since has been fixed.

**Comment by LeCoupa** [comment]
Thank you, I don't know why but it was using `0.1.10`.
