### ISSUE TITLE
Adding {{> UI. contentBlock }} to ionNavBar?

### ISSUE THREAD

**Issue by LeCoupa** [meteoric/meteor-ionic#55]
When working with the `ionNavBar` component, the content changes every time we go to a new route. This is due to the different `yield` helpers in the template that seem to reinitialize themselves.

How can I define just one time the content inside the ionNavBar and make it the same across all routes?

Would it not be a good solution for that to add `{{> UI. contentBlock }}` inside the `ionNavBar` template? (like it is for `ionHeaderBar`, `ionFooterBar`, `ionSubheaderBar`...)

This would not prevent users to define their own `yield` helpers in `{{> UI. contentBlock }}` if they want to.

**Comment by nickw** [comment]
The entire purpose of `ionNavBar` is to dynamically display titles and buttons based on routes. If you want a static bar you will want to use a `ionHeaderBar`.

**Comment by LeCoupa** [comment]
Alright, thank you!
