### ISSUE TITLE
Hide nav-bar on specific pages?

### ISSUE THREAD

**Issue by Batmunkh** [meteoric/meteor-ionic#57]
Is there a way to hide nav-bar on specific pages? I've found out on the vanilla ionic framework you just put a hide-nav-bar="true" option and it works. But I can't seem to figure out how to do it in meteoric-ionic.

Thanks

**Comment by nickw** [comment]
Ah yeah I haven't come across that use case myself, so haven't implemented it. For now I would probably just throw something in the `rendered` callback of that template that hides the header:

```
Template.myTemplate.rendered = function () {
  $('.bar-header').hide();
  $('.content').removeClass('has-header');
}
```

Then you might have to reset them when you leave:
```
Template.myTemplate.destroyed = function () {
  $('.bar-header').show();
  $('.content').addClass('has-header');
}
```

I'll see if it's easy enough to add this to the core.

**Comment by Batmunkh** [comment]
Thanks a lot.

**Comment by rohanray** [comment]
Hi @nickw, first of all thanks a lot for this wonderful package!

I have a use case where in I need to hide the nav-bar. I used your suggestion and it just works perfectly fine. May be you can include it in the meteoric package. One use case is 'splash screen' on app loading wherein a splash image is displayed on the whole screen with probably a loading icon. This is my use case indeed :) but I think it can be a common use case for a lot of apps.
