### ISSUE TITLE
Header not fixed if input active and page not scrollable

### ISSUE THREAD

**Issue by geritol** [meteoric/meteor-ionic#59]
Just encountered a strange issue.
Headers are fixed nicely. But if you click in a form, headers start to scroll with the content. Strange thing that this do not occur when the page is scrollable.

**Comment by nickw** [comment]
Yeah I've noticed this particularly in modals. I believe it's something to do with native keyboards, and Ionic has a Cordova plugin that will probably fix it: https://github.com/driftyco/ionic-plugins-keyboard.
