### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by nickw** [meteoric/meteor-ionic#6]
http://ionicframework.com/docs/nightly/api/service/$ionicPopup/

**Comment by rclai** [comment]
Would it be a long way off if I suggested using Sweet Alert?

https://github.com/t4t5/sweetalert

**Comment by nickw** [comment]
Well I think we want to mimic Ionic's native-inspired design, which we get for free by including their CSS framework, so I'm not sure sweetalert really buys us anything. But thanks for the suggestion.

If anyone's interested in implementing this component themselves, take a look at the [action sheet](https://github.com/meteoric/meteor-ionic/tree/master/components/ionActionSheet) component to see how a similar component is implemented.

**Comment by sircharleswatson** [comment]
It looks like this component is ready? Can we update the atmosphere package so I can use it? :)

**Comment by nickw** [comment]
Ah right, it's in 0.1.17 on Atmosphere. Closing this.

**Comment by sircharleswatson** [comment]
Thanks @nickw . I'm loving working with Meteoric so far!
