### ISSUE TITLE
Latest meteor update to 1.0.3.1 breaks meteoric:ionicons-sass

### ISSUE THREAD

**Issue by AnkitTheCoder** [meteoric/meteor-ionic#61]
After the meteor update, fourseven:scss errors out. 
As per their github issue (https://github.com/fourseven/meteor-scss/issues/60), trying the following is a work-around:

    meteor add fourseven:scss@=2.0.0-beta_1

However, once the packages are downgraded, starting the app gives the following:

```
Error while running for mobile platforms: Errors prevented bundling:
While building the application:
client/lib/less/app.scss: Scss compiler error: undefined
{
"status": 1,
"file": "/.../client/lib/less/app.scss",
"line": 2,
"column": 9,
"message": "file to import not found or unreadable:
.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons\nCurrent dir:
/.../client/lib/less/"
}
```

Unlike the installation instructions, trying to restart the app does not fix this issue.
The only way I was able to move forward was to remove the following line from my app.scss

    @import '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons';

**Comment by nickw** [comment]
I don't think this has anything to do with Meteor 1.0.3.1, it sounds like 2.0 version of `fourseven:scss` has possibly changed the way it handles import paths. For now we only support the 1.x version of `fourseven:scss`.
