### ISSUE TITLE
StatusBarStyle should dynamically adapt to background

### ISSUE THREAD

**Issue by nickw** [meteoric/meteor-ionic#62]
If your main nav bar uses a dark background with light text and your modals use a light header bar with dark text, then your status bar text will be unreadable when modals are open. We should be able to use [the methods provided by org.apache.cordova.statusbar](https://github.com/apache/cordova-plugin-statusbar/blob/master/doc/index.md#methods) to change the style dynamically.

![screen shot 2015-02-01 at 6 46 31 pm](https://cloud.githubusercontent.com/assets/3907/5995242/fdbd96da-aa42-11e4-81ed-47e4eac12cab.png)

![screen shot 2015-02-01 at 6 44 50 pm](https://cloud.githubusercontent.com/assets/3907/5995243/01b36c9c-aa43-11e4-933d-054f4274cb6a.png)

**Comment by nickw** [comment]
I'm not sure this will be possible to do dynamically since we can't currently read the current status bar style in order to revert to it.

Instead, I think it might be better to just provide callbacks for `IonModal.show()` and `IonModal.hide()` and all devs to change the status bar style themselves.

**Comment by dennisharrison** [comment]
@nickw I agree on passing that around explicitly.
