### ISSUE TITLE
SideMenuContainer: Uncaught TypeError: Cannot read property 'side' of null

### ISSUE THREAD

**Issue by fbeenaerts** [meteoric/meteor-ionic#63]
ionSideMenuContainer.created always results in Uncaught TypeError: Cannot read property 'side' of null

When **removing** next code in meteoric_ionic.js, the problem seems to be solved:
Template.ionSideMenuContainer.created = function () { this.side = this.data.side || 'both'; };   

Moreover in the app under *meteoric/demo*, this piece of code does not exists.

**Comment by nickw** [comment]
This was fixed over the weekend but I haven't pushed a new version to Atmosphere yet. I'll plan on doing that today, but in the meantime you can symlink the repo into your packages directory if you want.
