### ISSUE TITLE
Problem switching to ruby-sass

### ISSUE THREAD

**Issue by rizkysyazuli** [meteoric/meteor-ionic#65]
I just switched to the ruby-based [grigio:ruby-sass](https://atmospherejs.com/grigio/ruby-sass) package because there's several sass features that doesn't seem to be supported by the node-based [fourseven:scss](https://atmospherejs.com/fourseven/scss) (ex: some color functions and unable to use maps in an @each).

But now i'm getting this error:

    While building the application:
    error: conflict: two packages included in the app, grigio:ruby-sass and
    fourseven:scss, are both trying to handle .scss
    error: conflict: two packages included in the app, grigio:ruby-sass and
    fourseven:scss, are both trying to handle .sass

Is your package specifically requires the fourseven:scss package? Because i already removed the package. So why is it still processing .scss files?

Am i asking at the wrong place, btw?

**Comment by nickw** [comment]
Yeah, it is a dependency in `meteoric:ionic-sass`, I have an issue open to remove the dependency: https://github.com/meteoric/ionic-sass/issues/1
