### ISSUE TITLE
Dynamic ionic path

### ISSUE THREAD

**Issue by linhkurt** [meteoric/meteor-ionic#66]
Hi all,

I want to implement a dynamic menu list (menu content is fed through menusList collection), each menu item is routed to different path (also from menusList)
<pre><code>
MenusList = new Meteor.Collection('menusList');
MenusList.insert(  	
{
  		title: 'About Us',
  		path: 'aboutus'
});
MenusList.insert(
{
  		title: 'Product Catalog',
  		path:'catalog'
});
</pre></code>
...(10 menus more)

How can I achieve the dynamic data binding in meteoric, something like
<pre><code>
{{#ionList}}
{{#each menus}}
      {{#ionItem path="{{path}}" iconLeft=true iconRight=true}}
          {{> ionIcon icon="ios-checkmark" class="positive"}}
          {{title}}
          {{> ionIcon icon="ios-arrow-right"}}
        {{/ionItem}}
{{/each}}
{{/ionList}}
</pre></code>
Because  <code>{{ionItem path ={{path}} ..... }}</code>is not supported, i dont know how to render this list with dynamic routes. If anyone has done this before, please share the idea, thank you!

**Comment by benstr** [comment]
You are right, you cannot pass spacebars into another spacebars but you can pass a template helper or a key from `this`. In your case this would work.

```
{{#ionItem path=path iconLeft=true iconRight=true}}
```

Here is what happened... 

anything wrapped in `" "` then it is considered a literal string. If it does not have the parentheses then the template will look for javascript to provide the string dynamically.

P.S. Here is a Template Helper example...

```
Template.mainMenu.helpers({
  pathUrl: function(){
    return "/"+this.path
  }
});
```

```
{{#ionList}}
  {{#each menus}}
    {{#ionItem path=pathUrl iconLeft=true iconRight=true}}
      {{> ionIcon icon="ios-checkmark" class="positive"}}
      {{title}}
      {{> ionIcon icon="ios-arrow-right"}}
    {{/ionItem}}
  {{/each}}
{{/ionList}}
```

**Comment by linhkurt** [comment]
Thank you very much benstr, it works like a charm!

**Comment by linhkurt** [comment]
Thank you very much benstr, it works like a charm.
Now I understand more about how it works.

**Comment by benstr** [comment]
@linhkurt good to hear. Please close this issue.
