### ISSUE TITLE
Publish the code for the demo at: http://meteoric.github.io/

### ISSUE THREAD

**Issue by elie222** [meteoric/meteor-ionic#67]
I want to add an ionSideMenu to my app and seeing as there's very little documentation and no examples, I haven't been able to work it out yet. If we could get the example code that would make things much easier, seeing as it shows exactly how each component is used.

Keep up the great work!

**Comment by nickw** [comment]
Here ya go: https://github.com/meteoric/demo

**Comment by benstr** [comment]
You mean this? https://github.com/meteoric/demo

**Comment by benstr** [comment]
hahahaha

**Comment by elie222** [comment]
Thanks a lot for the super quick responses

**Comment by nickw** [comment]
:)
