### ISSUE TITLE
Cannot read property 'side' of null

### ISSUE THREAD

**Issue by dcsan** [meteoric/meteor-ionic#69]
I've setup a basic app using meteoric, which runs on my machine :)
however it doesn't work for someone else i'm collaborating with, on a clean checkout

it could be that we have an error in the CSS but its odd that one machine works fine and another one doesnt... 

error and error point is below:

```
.
meteoric_ionic.js:2718 Uncaught TypeError: Cannot read property 'side' of null
.

Template.ionSideMenuContainer.created = function () {                                                                  // 5
  this.side = this.data.side || 'both';                                                                                // 6
};                                                                                                                     

```

**Comment by nickw** [comment]
Check the version of `meteoric:ionic` in the `.meteor/versions` file. It sounds like they have an old version.
