### ISSUE TITLE
sideMenu added on both sides automatically

### ISSUE THREAD

**Issue by igandhi** [meteoric/meteor-ionic#74]
Hey, great work here!

Whenever I add a sideMenu on the left, an empty sideMenu is automatically added on the right side. Is there a way to have the menu only on one side? 

Also, is there a way to trigger the menu just by the sideMenu button on top-left or top-right instead of slide gesture across the phone's screen?

Thanks!

**Comment by maersu** [comment]
[Disable one site](https://github.com/meteoric/meteor-ionic/blob/master/components/ionSideMenuContainer/ionSideMenuContainer.js#L24)
```
{{#ionSideMenuContainer side="left"}}
                {{#ionSideMenus}}
...
```

Supress swipe

```javascript
Template.templateName.rendered = function () {
    IonSideMenu.snapper.settings({touchToDrag: false});
};
```

**Comment by nickw** [comment]
Yep, thanks @maersu !
