### ISSUE TITLE
Version 0.1.13 breaks build for ios/android

### ISSUE THREAD

**Issue by maersu** [meteoric/meteor-ionic#78]
Hi,

Thanks for your great work!

I'm having trouble with 0.1.13 and building for ios/android

```
meteor create test
cd test/    
meteor add-platform ios #or android
meteor add meteoric:ionic
meteor run ios #or android
```
`run ios`/`run android` throws the following error (build also fails with the same error):
```
Error while running for mobile platforms: Error running /Users/maersu/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: version not found: 1.0.3 : com.ionic.keyboard/1.0.3
```
([gist](https://gist.github.com/maersu/ab2c66d8efe68e4e6fab) with complete output)

It works with forcing to version `meteoric:ionic@0.1.12`

Any help would be appreciated :)

**Comment by nickw** [comment]
Hmm, I'm not sure why it's not finding 1.0.3 of this plugin: https://github.com/driftyco/ionic-plugins-keyboard

**Comment by idmontie** [comment]
@nickw I'm guessing by the commits, you've already noticed there is no 1.0.3 release anymore.  It should be 1.0.4. https://github.com/driftyco/ionic-plugins-keyboard/releases

**Comment by maersu** [comment]
@idmontie do you have the problem too? if I'am the only one it's maybe related to my system.

**Comment by nickw** [comment]
@maersu no, others are experiencing the issue too. It looks like v1.0.3 got removed for some reason. I'll be pushing 0.1.14 today that will depend on ionic-keyboard 1.0.4

**Comment by idmontie** [comment]
@maersu Yes, I have the same problem right now:

```
$ meteor run ios
Error while running for mobile platforms: Error running                            
/.meteor/packages/meteor-tool/.1.0.40.l6r7jf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: version not found: 1.0.3 : com.ionic.keyboard/1.0.3
```

@nickw Great to hear! :smiley:

**Comment by mikeconstable** [comment]
I managed to workaround this a couple of days back by manually changing the version from 1.0.3 to 1.0.4 in the star.json file in the .meteor/local/build folder in my app. Problem went away after that. 

Welcome the update @nickw mentioned though.

**Comment by nickw** [comment]
Ok guys, v 0.1.14 has been published.

**Comment by maersu** [comment]
hi @nickw,
Amazing. Works like a charm, now! 

Thanks a lot.

**Comment by markclayton** [comment]
Looks like `meteor:ionic@0.1.17` is still configured to depend on `cordova:com.ionic.keyboard@1.0.3`. Forcing back down to version `meteoric:ionic@0.1.14` didn't solve the problem this time.
