### ISSUE TITLE
scrollDelegate

### ISSUE THREAD

**Issue by dcsan** [meteoric/meteor-ionic#79]
I see that Scroll is on the list of TODOs
does that refer to the scrollDelegate? 
http://ionicframework.com/docs/api/service/$ionicScrollDelegate/

I have a need that when new items are added to a list view to scroll to reveal them, like in a chat.

If someone could give a general idea of what needs porting from ionic I maybe able to take a look. but not sure where to start implementing things like delegates.

**Comment by dcsan** [comment]
related ex
http://forum.ionicframework.com/t/how-to-make-the-sccollbar-of-content-element-scroll-down-to-the-bottom-automatically/393/3

**Comment by nickw** [comment]
We're currently achieving this same functionality in an app by just changing/animation the `scrollTop` property of the relevant `content` area.

**Comment by dcsan** [comment]
got it. for anyone else I had to do this

make sure the ionList has a targetable tag (I guess you could nest another div but performance blah)

```
#stream {
  // these are required for autoscrolling
  width 100%
  height 100%
  overflow scroll
}
```

and then code using velocityJS


```js
    $('#streamFooter').velocity('scroll',
      {
        duration: 500
        easing: "easeinout"
        offset: 500    # offset on the target div only
        container: $("#stream")
      }
    )
  
```

```jade
  +ionView

    +ionContent

      +ionList(id='stream')
        each messages
          +ionItem(id="{{timestamp}}")
            {{> UI.dynamic template=template data=messageObject}}

        +ionItem
          #streamFooter
            br
            p ....
            hr

```

streamFooter is the target item velocity will scroll to.

@nickw maybe we can make a "tips" or wiki for these type of things?

**Comment by elGusto** [comment]
Or without velocity for people who don't use it:

Template:

     {{#ionView}}
        {{#ionContent}}
           <div class="scroll-bottom-wrapper">
              {{#each items}}
                   // your stuff
              {{/each}}
           </div>
        {{/ionContent}}
     {{/ionView}}


Template.rendered function:

      //scroll to bottom when page is rendered
      $('div.scroll-bottom-wrapper').scrollTo($('div.scroll-bottom-wrapper')[0].scrollHeight);

     //blaze uihooks
      this.find('.scroll-bottom-wrapper'')._uihooks = {
         insertElement: function (node, next) {
            $(node).insertBefore(next);
            var scrollDiv = $('div.scroll-bottom-wrapper')[0];
            $('div.scroll-bottom-wrapper').scrollTo($('div.scroll-bottom-wrapper')[0].scrollHeight);
         } 
      }

CSS for the wrapper div is like in comment above.

Of course you can put your own animations to make things B-E-A-utiful.

**Comment by torayeff** [comment]
@elGusto for some reason it does not work for me, what can be the problem?
