### ISSUE TITLE
How stable is this package? 2/17/2015

### ISSUE THREAD

**Issue by ccorcos** [meteoric/meteor-ionic#82]
I'm thinking about use this for a new project :)
Is is this package ready for use?

**Comment by nickw** [comment]
We (Differential) are using it on a large client project right now and haven't run into any issues with it yet. The client is very happy with how "native" it feels and is now converting another app from Bootstrap to Meteor-Ionic.

**Comment by ccorcos** [comment]
Thats what I wanted to hear :+1:

**Comment by benstr** [comment]
I am using it for a nationwide enterprise iPad app right now. Client is very happy and I enjoyed using it.
