### ISSUE TITLE
Unable to change Modal header bar color

### ISSUE THREAD

**Issue by rizkysyazuli** [meteoric/meteor-ionic#85]
In the source, i see a `barClass` helper and few other. are they usable? because implementing it doesn't seem to have any effect.

    {{#ionModal focusFirstInput=true title="Products" barClass="bar-energized"}}
        ....
    {{/ionModal}}

**Comment by nickw** [comment]
Oops, yeah it looks like PR #73 from @fpoirier1 forgot to allow passing a custom `barClass`. @fpoirier1 would you be available to add that as a new PR?

@rizkysyazuli in the meantime you can do something like this:
```
{{#ionModal customTemplate=true}}
  <div class="bar bar-header bar-energized">
    <h2 class="title">Products</h2>
  </div>
  <div class="content has-header overflow-scroll">
    ...
  </div>
{{/ionModal}}
```

Also I believe `focusFirstInput` is now true by default, so you can save a few keystrokes on that.

**Comment by rizkysyazuli** [comment]
Hmm. Funny. It doesn't seem to respect the `customTemplate` option. The "custom" markup is still wrapped inside the default markup. Now i'm seeing two headers.

Here's the HTML output:

    <div class="modal">

      <div class="bar bar-header bar-stable">
        <button data-dismiss="modal" class="button button-icon"><i class="icon ion-ios-close-empty"></i></button>
        <h2 class="title"></h2>
      </div>
      <div class="content has-header overflow-scroll">
        
        <div class="bar bar-header bar-energized">
            <h2 class="title">Find Products</h2>
        </div>
        <div class="content has-header overflow-scroll">
          ...
        </div>

      </div>
    </div>

**Comment by nickw** [comment]
Hmm are you running the latest version (0.1.14)?

**Comment by rizkysyazuli** [comment]
yep. just updated. still the same. if you need me to provide any other info. just let me know.

**Comment by nickw** [comment]
Can you post your template code?

**Comment by rizkysyazuli** [comment]
Here you go.

```html
<template name="trackerSearch">

    {{#ionModal customTemplate=true}}
        <div class="bar bar-header bar-energized">
            <button data-dismiss="modal" class="button button-icon"><i class="icon ion-ios-close-empty"></i></button>
            <h2 class="title">Find Products</h2>
        </div>
        <div class="content has-header overflow-scroll">
            
            <div class="list">
                <div class="item item-input-inset">
                    <label class="item-input-wrapper">
                        <i class="icon ion-search placeholder-icon"></i>
                        <input type="text" placeholder="Search" value="{{searchQuery}}">
                    </label>
                </div>

                {{#each products}}
                    {{#ionItem path="trackerDetail" buttonRight=true class="item-icon-right item-thumbnail-left"}}
                        <img src="{{image}}" alt="">
                        <h2 class="energized">{{title}}</h2>
                        <p>Origin: {{origin.city}}, {{origin.country}}</p>
                        
                        <i class="icon ion-chevron-right energized"></i>
                    {{/ionItem}}
                {{/each}}
            </div>

        </div>
    {{/ionModal}}

</template>
```

I can also give you the source code access if you need it. I have it on Bitbucket. just tell me your username.

**Comment by nickw** [comment]
Yeah, that's very strange, I'd definitely be interested in seeing your code. My bitbucket username is `nickwientge`.

**Comment by rizkysyazuli** [comment]
Done, check your Bitbucket inbox.

There's not much stuff right now. So it should be easy to look around. The product finder templates is in `client/templates/tracker` folder.

Btw, a bit OOT. When running on iOS simulator, there's an extra space in the header bar. Hope you don't mind having a look at this as well.

Thx a lot!

![screenshot 2015-02-25 15 25 57](https://cloud.githubusercontent.com/assets/152221/6367240/f656e108-bd02-11e4-8794-0fb2ae024f01.png)

**Comment by nickw** [comment]
> Hmm are you running the latest version (0.1.14)?

> yep. just updated. still the same. if you need me to provide any other info. just let me know.

Your app is showing `0.1.12` in `.meteor/versions` - I updated it and it works fine.

![screen shot 2015-02-25 at 7 20 54 am](https://cloud.githubusercontent.com/assets/3907/6373342/ea016426-bcbe-11e4-85b0-b44834ac53a5.png)

**Comment by nickw** [comment]
Nice looking app btw :)

**Comment by rizkysyazuli** [comment]
the interface is all ionic. so that's thx to you.

anyway, all good now. didn't know why it didn't update before. thx again for taking the time.

**Comment by gwendall** [comment]
Just bumped into the same issue. See https://github.com/meteoric/meteor-ionic/pull/243
