### ISSUE TITLE
align-title="left"

### ISSUE THREAD

**Issue by Mantak** [meteoric/meteor-ionic#86]
can i set the title align of header or footer ?

http://ionicframework.com/docs/api/directive/ionHeaderBar/

**Comment by nickw** [comment]
Yeah, I'm not sure why Ionic uses a custom attribute on the parent element like that, you can just add `title-left`, `title-center`, or `title-right` classes directly to the `<h1>` element itself.

**Comment by linhkurt** [comment]
Setting title-center on <h1> element on Android does not work. It always attach title-left eventually.
https://github.com/meteoric/meteor-ionic/blob/master/components/ionHeaderBar/ionHeaderBar.js#L6
<code>
if (Platform.isAndroid() && !this.alignTitle) {
      $title.addClass('title-left');
      return;
    }
</code>

**Comment by hoittr** [comment]
Can confirm. Ran into the same bug.

**Comment by Loschcode** [comment]
Ran into it, anyone has a solution here ?
