### ISSUE TITLE
Crosswalk Project

### ISSUE THREAD

**Issue by joshua1** [meteoric/meteor-ionic#90]
Hi,
Any walkthrough or pointers on how to include the crosswalk project webview for android devices?

**Comment by teknologist** [comment]
Hi @joshua1,
Have you checked this : 
https://meteor.hackpad.com/Building-Meteor-app-with-Crosswalk-kHKh4DzGxFQ
?

I am going to give it a try at a later stage. Let me know if you test it.

Crosswalk bins have been updated since that post, so check the latest webviews in the Intel directory.

**Comment by nickw** [comment]
Yeah, that Hackpad is the way to go. I haven't tried it yet myself though.

**Comment by crapthings** [comment]
Can't compile crosswalk with meteor, i've tried solve that on hackpad with crosswalk from v8.x to v12.x all failed, wish that will work on 1.0.4 with upgraded cordova.
