### ISSUE TITLE
SideMenus content based on route/path

### ISSUE THREAD

**Issue by jamgold** [meteoric/meteor-ionic#92]
Thank you very much for your package, it helps me a lot. Unfortunately I can not figure out how to have different side menus per route, since the example only renders side menus in the global layout.

Also, the relationship of ionSideMenuContent is not quite clear to me. Is it that all layouts with side menus need to be wrapped in ionSideMenuContainer and the main page content goes in ionSideMenuContent?

I tried contentFor ionSideMenus, but that didn't work.

**Comment by maersu** [comment]
@jamgold for different SideMenuContent you can use [IronRouter regions](https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#rendering-templates-into-regions-with-javascript)

**Comment by jamgold** [comment]
@maersu  Brilliant, thanks
