### ISSUE TITLE
Enhancement: Optionally hide tabbar Ionic style

### ISSUE THREAD

**Issue by connor-baer** [meteoric/meteor-ionic#94]
I'm working on a chat app with a tabbar. I would like to hide the tabbar to make room for the message input field in the messages view. Ionic supports this feature with the addition of a class:

"To hide the tabbar but still show the content, add the `tabs-item-hide` class." (http://ionicframework.com/docs/components/#tabs)

I've tried using a different layout for the messages view with iron:router, but then the ionic transitions don't work anymore.

Please add this as a feature or point me in the right direction on how to do it. 

Thanks!

**Comment by nickw** [comment]
You should be able to do something similar to #83

**Comment by connor-baer** [comment]
Thanks, that hides the tabbar. 

However, ionView does not adjust to take over the extra space at the bottom. It leaves an empty rectangle, although it sets the tabbar's display: none.
For now I'll go back to using different layouts. Would be nice to have an easy implementation of this though.

(Unfortunately I have no suggestions on how to do it, I'm quite new to coding.)

**Comment by nickw** [comment]
Right, that's what the Session variable is responsible for. In your case I think you would need to toggle `Session.set('hasTabs', false);` and `Session.set('hasTabs', true);`

**Comment by connor-baer** [comment]
Perfect! That does it. Thanks so much.
