### ISSUE TITLE
Add dependencies to package.js

### ISSUE THREAD

**Issue by lorensr** [meteoric/meteor-ionic#96]
![image](https://cloud.githubusercontent.com/assets/251288/6433601/e545da18-c027-11e4-82ee-703ed9049bed.png)

The way to do this automatically is adding these lines to `Package.onUse`:

`api.imply('iron:router@[minimum version]')`

See for example https://github.com/parlaywithme/starter-pack/blob/master/package.js

**Comment by nickw** [comment]
Yeah, my thinking was that this way users could bring their own version of Ionic - or use a different preprocessor - if they wanted. Might revisit this later based on user feedback.

**Comment by lorensr** [comment]
I see, well for feedback – I sent a list of commands needed to a friend who
is starting an iconic app to try to convince him that it would be easy to
use meteor for his project, and the list could have been half as long if
there was just one thing to add. Also, I'm guessing there are people who
don't read the Guide.md or skip past the top part to get to usage examples,
and they at first just install meteoric:ionic and have trouble getting it
to work.
