### ISSUE TITLE
Not hide footer on keyboard open (feature)

### ISSUE THREAD

**Issue by geritol** [meteoric/meteor-ionic#99]
Hi!
Is there a way to not hide the footer when the keyboard is open?
(It would be great when adding eg. chat features when the textarea could be in the footer.)

Thanks for the help and the awesome work!

**Comment by geritol** [comment]
https://github.com/driftyco/ionic/issues/957

**Comment by nickw** [comment]
Yes, just add `data-keyboard-attach` to the element: https://github.com/meteoric/meteor-ionic/blob/master/components/ionKeyboard/ionKeyboard.js#L50

**Comment by geritol** [comment]
Thanks! Seems working.
is there a way to add it to eg. a footer created like this?

    {{#ionFooterBar class="bar-light"}}
    {{/ionFooterBar}}

**Comment by nickw** [comment]
Unfortunately not until I get around to implementing #60. In the meantime here's what I'm doing in my app:

```
<div class="bar bar-footer bar-stable" data-keyboard-attach>
  <form class="item-input-wrapper form-send-message">
    <input type="text" placeholder="Enter Message…" name="message">
    <button class="button button-positive button-clear" type="submit">Send</button>
  </form>
</div>
```

**Comment by geritol** [comment]
Thanks fot the quick answer!

**Comment by woniesong92** [comment]
Thank you so much. @nickw this helped me tremendously too. So can you add any angular directive using `data-*`?
